### ISSUE TITLE
Provide a framework to replace check_files.php

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#102]
[check_files.php](https://github.com/MarcusBarnes/mik/blob/master/extras/scripts/check_files.php) is becoming long and bloated, and is also becoming more specific to SFU's migration. It would be great to provide a wrapper script that allowed people to add specific tests easily. This script would iterate down a directory tree and allow the scripts to check specific files.

It would be interesting to see if we could use PHPUnit for this. An example of using PHPUnit to test non-code that I've played with is [Islandora Stack Tests Suite](https://github.com/mjordan/islandora_stack_tests).

**Comment by MarcusBarnes** [comment]
:thumbsup:

**Comment by mjordan** [comment]
Closing in favour of #302.
