### ISSUE TITLE
Allow for the creation of metadata only

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#109]
We have a use case with the Lake District Collection where we want to get MODS documents for all of the books so they can be manually edited before migrating the collection. We could generate MODS from CONTENTdm with a bespoke script but we'd lose the ability to use fetcher and metadata manipulators, etc.

A simple implementation would be to add a 'metadata_only' value to the WRITER section of .ini files and if this was set to true, return from the `$writer->writePackages()` method just after `$this->writeMetadataFile()`. I've tested this with the three Cdm writers and it works as expected (I only had to add 'return;' in the right place to test it). Using this approach will require a bit more work for the CsvSingleFile writer but not a lot.

The workflow for using this option would be to generate the metadata using this option, edit it, generate the complete packages, replace the metadata files generated in the last step with the edited ones, and then batch load into Islandora. This issue does not address how the metadata files are replaced and I would consider that to be out of scope for MIK.

**Comment by MarcusBarnes** [comment]
For the [CdmNewspaper writer](https://github.com/MarcusBarnes/mik/blob/master/src/writers/CdmNewspapers.php) class, this feature has already been implemented with the datastreams property set within the Writer parent class.  In the Writer section of the configuration file, you'd only list datastreams[] = "MODS"; it would then skip writing all other default output files other than the MODS.xml file.  The same pattern can be applied to the other writer classes.

**Comment by mjordan** [comment]
Nice! I'll implement this in the other Writers, if that's OK.

**Comment by MarcusBarnes** [comment]
@mjordan Yes - that would be awesome if you could do that.  Thank you.

**Comment by mjordan** [comment]
I've implemented your checking for DSIDs in the CdmSingleFile, CdmPhpDocuments, and CsvSingleFile writers. Unlike with the CdmNewspapers writer where the DSIDs are known in advance, for the SingleFile writers, the non-metadata file can be OBJ or something else, depending on the content model. In other words, we can't specify a DSID like we do for MODS because the writer is used to create ingest packages for a variety of Islandora content models. So, I've chosen (for now) to not check for a DSID other than MODS or DC. This means that we only write the non-metadata file if no datastream IDs are specified in the datastreams[] configuration option. You can still specify MODS for example and get only the expected .xml file.

I still need to do some testing on the CsvSingleFile writer.

**Comment by mjordan** [comment]
@MarcusBarnes I've tested on CsvSingleFile writer, and had to move some stuff around within that class file - can you take a look at https://github.com/MarcusBarnes/mik/commit/6804a8ad45ea8f541194e4ddfe0ddf667e219ad1 ?. I am unclear what `$enforce_metadata_only` does. Is that variable still necessary?

**Comment by MarcusBarnes** [comment]
@mjordan  `$enforce_metadata_only` is related to Mark Cooper's use-case and pull-request: https://github.com/MarcusBarnes/mik/pull/56/files  It would be good to preserve the functionality for his use-case.

**Comment by mjordan** [comment]
OK, thanks. I'll make sure it remains intact.

**Comment by MarcusBarnes** [comment]
:thumbsup:

**Comment by mjordan** [comment]
@MarcusBarnes sBarnes OK, I've confirmed that @mark-cooper's functionality is unchanged by my recent work on #109. I will email you some test data if you have time to confirm.

**Comment by MarcusBarnes** [comment]
@mjordan That would be great.  Thanks.

**Comment by mjordan** [comment]
Closed wiit https://github.com/MarcusBarnes/mik/pull/110.
