### ISSUE TITLE
Provide documentation for toolchains in the wiki?

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#112]
Would it be desirable and useful to have a wiki pages that describe how to use MIK for various tool chains (for example, Cdm Newspaper)?   Currently, the main wiki page describes how to set up MIK with examples and there are pages for various manipulators.  Toolchains seem similar to use-cases.

**Comment by mjordan** [comment]
Yes it would. I can take a first crack at this.

**Comment by mjordan** [comment]
I've created a wiki page for the [CSV single file toolchain](https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CSV-single-file-objects). Let me know if you think it would act as a useful template for the others.

I'd like to provide a cookbook like the one I did up for [Islandora Feeds](https://github.com/mjordan/islandora_feeds/wiki/Cookbook) to document how to add extra elements to a MODS file using null mappings, how to write a post-write hook script, how to write a custom metadata manipulator, etc. Do you think the combination of the toolchain documentation and a cookbook would be sufficient documentation? We may want to st olici some feedback on the Islandora email list about this.

**Comment by mjordan** [comment]
All toolchains other than CONTENTdm books and CONTENTdm compound have full docs on the wiki. As part of our current cleanup sweep, I'll close this since docs for those two are forthcoming.
