### ISSUE TITLE
Provide configuration option to set the CSV reader's enclosure character

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#118]
League CSV uses the double quotation mark as the default field enclosure character. We should provide a configuration option to allow the setting of this.

**Comment by mjordan** [comment]
I've added this option, and while I was in there I added the option to define the CSV escape character and made [FETCHER] field_delimiter setting optional, giving it a default of ','.

* To test that the field_delimiter setting is now optional, comment it out in the cartoons_config.ini file and run the CSV toolchain.
* To test the new [FETCHER] field_enclosure option run the CSV toolchain using [this csv file](https://gist.github.com/mjordan/e0d6439ab6ad549c4965). Before you run mik, add the setting "field_enclosure = '|'" to the FETCHER section.
* To test the [FETCHER] escape_character, replace the letter I in CSV record 7904 with a pipe, and add the following line to the FETCHER section of the config file: "escape_character = '~'". Then run MIK.

**Comment by MarcusBarnes** [comment]
@mjordan I have successfully tested that the field_delimiter setting is optional. Thanks.

**Comment by MarcusBarnes** [comment]
@mjordan I have successfully tested that the new [FETCHER] field_enclosure option using the test csv file that uses the bar character as an enclosure.

**Comment by MarcusBarnes** [comment]
@mjordan For the test of the [FETCHER] escape_character in your [comment above](https://github.com/MarcusBarnes/mik/issues/118#issuecomment-170779543), what was the expected result?

**Comment by mjordan** [comment]
Merged with c79258770a3809ecb8e82b45d0b13b3c21001dc2. I'll open a separate issue about the inclusion of the escape character in the CSV field values.

**Comment by MarcusBarnes** [comment]
:thumbsup:  Thank you @mjordan
