### ISSUE TITLE
Ignore Thumbs.db, ._.DStore, etc

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#119]
The CSV single file toolchain (and the CSV compund toolchain when it is developed) must ignore all occurrences of Thumbs.db (Windows) and .DS_Store / ._.DStore (Mac) when scanning directories. We may need to account for how the various operating systems define hidden files as well, since we generally don't want to include them in Islandora ingest packages.

**Comment by mjordan** [comment]
This would make an excellent post-write hook script. Define a list of files to delete, iterate down through the output directory, and if they are found, blast them.

**Comment by mjordan** [comment]
The ever perspicacious @MarcusBarnes points out that some dot files can be generated simply by viewing a directory, so it would be very useful to be able to run this post-write hook script in "standalone" mode too, so it could be run just before loading a set of packages into Islandora.

**Comment by mjordan** [comment]
I've just pushed a 'remove_files.php' script to branch issue-119 that recurses down and directory and removes files whose name is in the specified list. There is a logging option:

```
php remove_files.php -d=/target/directory -l=/path/to/log/file
```

If not included, messages are printed to STDOUT.

@MarcusBarnes can you test on your Mac? Works as intended in Windows.

**Comment by MarcusBarnes** [comment]
@mjordan  Yes - I'll test on a Mac.  If it runs as expected, I'll create a pull-request and merge.  Thanks.

**Comment by mjordan** [comment]
@MarcusBarnes don't merge, I need to fix some formatting/indentation issues.

**Comment by MarcusBarnes** [comment]
@mjordan OK.  Thanks for the warning.

**Comment by MarcusBarnes** [comment]
@mjordan The 'remove_files.php' script functions as expected.  Thank you.

I've pushed a small change.  The script will check that the log path exists and exits with a message if it does not.  This is to catch typos and similar erros when specifying the log path parameter.

@mjordan  Please feel free to create a pull request once you are happy with the formatting/indentation.  I'll then review and merge as appropriate.

**Comment by mjordan** [comment]
Fixed. I'd rather you merged issue-119 into master than do a PR - is that OK?

**Comment by mjordan** [comment]
OK, PR to merge issue-119 into master created.

**Comment by mjordan** [comment]
I'll close this and add a cookbook page for the feature.

**Comment by MarcusBarnes** [comment]
@mjordan Awesome.  Thanks.
