### ISSUE TITLE
Call to $writer->writePackages() in mik should have a $record_id parameter

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#12]
Passing a $record_id parameter to $writer->writePackages($metadata, $child_pointers); will give us convenient access to a unique ID to use for single-file content model ingest packages. Only backward compatibility issue will be at writers/CdmNewspapers.php line 57, but that is easily fixed by adding the new parameter to the end of writePackages().

To summarize, the call to $writer->writePackages() in mik should be:

```php
$writer->writePackages($metadata, $child_pointers, $record_id);
```

**Comment by MarcusBarnes** [comment]
First go at addressing this issue in commit ff107ad79133a27284417a7559da8f9548420a84.
