### ISSUE TITLE
Windows PowerShell and cmd shell cannot run post-write hook scripts

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#121]
When running MIK under the Windows cmd shell or PowerShell, post-write hook scripts fail and produce the error  `Fatal Error Unable to reattach to base address`, at least on Windows 7 Enterprise SP1 (64 bit). This does not happen when running MIK in Git Bash.

I will open an issue with [cocur/background-process](https://github.com/cocur/background-process), the component used to run these jobs.

**Comment by mjordan** [comment]
Here's the upstream issue: https://github.com/cocur/background-process/issues/15

**Comment by mjordan** [comment]
Commenting out `opcache.enable_cli=1` in php.ini resolves this issue.

**Comment by MarcusBarnes** [comment]
@mjordan :thumbsup:

**Comment by mjordan** [comment]
I'd like to repoen this issue and suggest that we set opcach.enabled_cli to 0 using a solution similar to the one we have used [here](https://github.com/MarcusBarnes/mik/blob/master/mik#L15) to set the default timezone.

**Comment by mjordan** [comment]
Tested on Linux with no side effects so merging into master.
