### ISSUE TITLE
Add option to write start time of the MIK job to mik.log

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#124]
It would be useful to write a log entry that indicated what time the job started. This could be done within src/config/Config.php, and the config option could look like `[CONFIG] log_start_time = TRUE`.

**Comment by MarcusBarnes** [comment]
The first variable set in the main MIK script is [`$time_start`](https://github.com/MarcusBarnes/mik/blob/master/mik#L9).  The logging is instantiated afterwards.

**Comment by mjordan** [comment]
I didn't add an option for adding the start time, since we don't provide an option for the "Completed in" log entry. Please test and merge at your convenience.

**Comment by MarcusBarnes** [comment]
Merged with pull-request https://github.com/MarcusBarnes/mik/pull/130.
