### ISSUE TITLE
CSV reader's escape character appears in ouput

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#129]
Related MIK issue: https://github.com/MarcusBarnes/mik/issues/118

If an escape character is used within a CSV value, it appears in the CSV reader's output. The maintainer of League CSV [has confirmed](https://github.com/thephpleague/csv/issues/149) that this is a [PHP bug](https://bugs.php.net/bug.php?id=55413).

For example, using this input CSV file, with the default escape character of `\`:

```
"first row, first field", "first \"row\", second field"
"second row, first field", "second row, second field"
"third row, first field", "third row, second field"
```
the reader returns `first \"row\", second field`, and not `first "row", second field`.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you for following up on this.  Much appreciated.
