### ISSUE TITLE
Add tests and other quality control features

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#132]
For the 1.0 milestone, it is desirable to enhance the ongoing quality of MIK by adding Unit Tests and other quality control features.  This is a general issue - please feel to make suggestions in this thread and break into more specific issues as required.

**Comment by mjordan** [comment]
Added some more tests for the CSV toolchain in c4cde1d1fa4d37eac3a4e2606a26b19b73a2565f. Test for fetcher manipulators isn't working for some reason.

**Comment by mjordan** [comment]
Maybe consider something like https://github.com/phpro/grumphp for code quality checks?

**Comment by MarcusBarnes** [comment]
:thumbsup:

**Comment by mjordan** [comment]
@MarcusBarnes I don't know how many more tests we should be adding. I was hoping to add some tests for the CONTENTdm toolchains but short of mocking up a CONTENTdm server I don't see how we can do that. Thoughts?

**Comment by MarcusBarnes** [comment]
@mjordan For sources like a CONTENTdm server, we may just have to document that they are examples and will likely need to be modified in order to work since they lie outside the main testing suite.  We can explain that we haven't included them in the main unit testing suite since we don't have regular access to a CONTENTdm server and there are issues if we try mocking up the API for ongoing testing purposes.

**Comment by mjordan** [comment]
Yeah, that's reasonable. Same goes for OAI-PMH toolchains. We do have fairly good test coverage of the CSV toolchains, although I would love to see someone well versed in PHPUnit testing review the existing test to see why some of them exhbit quirky behavior.

I'm happy to just document tests for those toolchains as you describe (i.e., they're impractical to write) on https://github.com/MarcusBarnes/mik/wiki/Information-for-developers. As for the "other quality control features", we now have MIK's input validation and also the Islandora Ingest Package QA Tool. Mabye we can lose this issue?

**Comment by MarcusBarnes** [comment]
@mjordan Yes - I think we can close this issue and create more specific issues as needed.

**Comment by mjordan** [comment]
OK, agreed. But mind if I open a PR based on this issue to remove "more tests" from the README.md file?

**Comment by MarcusBarnes** [comment]
@mjordan Sure.  That's sound good.  Thank you in advance.

**Comment by mjordan** [comment]
Obsolete, closing.
