### ISSUE TITLE
Write unit test for FITS

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#135]
Given all of paths, Java environment variables, etc. that are involved in getting FITS to run, it would be useful to be able to tell if FITS is working in a given environment. We should be able to write a PHPUnit test to do that.

Thanks to @rbos for the suggestion.

**Comment by MarcusBarnes** [comment]
:thumbsup:

**Comment by mjordan** [comment]
Our second test! Yay!

**Comment by mjordan** [comment]
@MarcusBarnes I've tested this on Linux and Windows, and it works. Can you merge into master?

**Comment by mjordan** [comment]
... but feel free to test on OS X first :smile:

**Comment by MarcusBarnes** [comment]
@mjordan I'll test on OS X first, then merge.  Thanks.

**Comment by MarcusBarnes** [comment]
@mjordan Works as expected on OS X.

**Comment by mjordan** [comment]
Merged after discussion with @MarcusBarnes.
