### ISSUE TITLE
Provide an OAI-PMH toolchain

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#142]
https://github.com/caseyamcl/phpoaipmh looks promising. OAI-PMH has no standard way of referencing content files like PDFs, etc. So each type of source repository (DSpace, etc.) would need its own file getter class.

**Comment by mjordan** [comment]
And maybe this would be useful for getting the URLs for linked content files: https://github.com/oscarotero/Embed/. For example, use OAI to get the metadata (which does not contain links to files) and then this component to parse out URLs on public pages corresponding to harvested objects.

**Comment by mjordan** [comment]
Some initial work in the issue-142 branch on this using the OAI-PMH component linked above. Using the following .ini, the new OAI-PMH fetcher will write records into the temp directory. 

```
[FETCHER]
class = Oaipmh
oai_endpoint = "http://arcabc.ca/oai2"
set_spec = unbc_scholars
temp_directory = "/tmp/oai_temp"
```
So the basics of an OAI-PMH fetcher work. But, an interesting question arises: The records retrieved via OAI-PMH are full XML. Do we continue to use a mappings file as with CONTENTdm and CSV (say with expath expressions in the source column) or use pure XSLT to transform the incoming XML records into MODS? If we choose the latter, do metadata manipulators still work, or do we need to create a new type of manipulator that works on the entire XML document, not just the individual elements?

OAI-PMH will likely not be the only source that provides full XML, so it might be worth thinking more generally about how processing incoming XML documents of arbitrary complexity may differ from the largely key => value data we've been dealing with so far in CONTENTdm and CSV.

**Comment by mjordan** [comment]
@MarcusBarnes as discussed, I'll continue with the whole-document XSLT approach for now so we can have some tires to kick.

**Comment by MarcusBarnes** [comment]
@mjordan Awesome.  Thanks.

**Comment by mjordan** [comment]
The issue-142 branch contains a working toolchain to harvest content using OAI-PMH from an [OJS](https://pkp.sfu.ca/ojs/) instance and create Islandora ingest packages containing one DC file and one PDF file. Here is a working .ini file:

```
; MIK configuration file for an OAI-PMH OJS toolchain.

[CONFIG]
config_id = oaitest
last_updated_on = "2016-06-12"
last_update_by = "mj"

[SYSTEM]
date_default_timezone = 'America/Halifax'

[FETCHER]
class = Oaipmh
oai_endpoint = "http://journals.sfu.ca/present/index.php/demojournal/oai"
set_spec = demojournal:ART
temp_directory = "/tmp/oaitest_temp"

[METADATA_PARSER]
class = dc\OaiToDc
xslt_path = "extras/scripts/oai_to_dc.xsl"

[FILE_GETTER]
class = OaipmhOjsPdf
temp_directory = "/tmp/oaitest_temp"

[WRITER]
class = OaipmhOjsPdf
output_directory = "/tmp/oaitest_output"

[MANIPULATORS]

[LOGGING]
path_to_log = "/tmp/oaitest_output/mik.log"
path_to_manipulator_log = "/tmp/oaitest_output/manipulator.log"
```

OAI-PMH does not provide a standardized way to indicate the URL of the PDF or other non-metadata content. As a result, the MIK filegetter and writer classes need to be specific to the source platform in order to scrape the URLs for the PDF (in the case of this toolchain) from the OJS HTML. Adding filegetters and writers for other source platforms like DSpace should be fairly easy as long as their URLs to content files can be scraped or otherwise determined.

Also note that this toolchain produces DC XML files, not MODS. Islandora automatically creates a MODS datastream from the DC, so generating a MODS outside of Islandora would be redundant.

(For the historical record, this toolchain was written in Dublin the weekend prior to the OR2016 conference.)

@MarcusBarnes can you test using this .ini file? You will need to run `composer update` and `composer dump-autoload` after switching to the issue-142 branch.

**Comment by mjordan** [comment]
Draft wiki page at https://github.com/MarcusBarnes/mik/wiki/Toolchain:-OAI-PMH-for-Open-Journal-Systems.

**Comment by MarcusBarnes** [comment]
@mjordan Awesome!  Yes, I'll test and get back to you.  Thank you.

**Comment by MarcusBarnes** [comment]
@mjordan I've done some initial testing and the main script appears to function as expected.   We will need to update src/config/Config.php since it expects a mapping_csv_path and creates an undefined index error when running --configcheck=all.  If you're comfortable with the code for this example OAI-PMH toolchain, please create a pull-request.  We can add an issue to fix the problem with --configcheck=all for toolchains without mapping files.

**Comment by mjordan** [comment]
@MarcusBarnes great catch on the --checkconfig oversight. I'll open a PR for work to date and then open an issue. Thanks for testing.

**Comment by mjordan** [comment]
Branch 142 merged.
