### ISSUE TITLE
Allow reuse of cached metadata if it exists

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#144]
It would speed up MIK jobs if fetchers could avoid re-fetching and filtering large record sets. One way to do this is to reuse any cached metadata if it exists. One possible implementation would be that if the SpecificSet fetcher manipulator is being used, the fetcher's getRecords() method could look to see if there is a corresponding metadata cache for each object and if there is, skip the refetch.

@MarcusBarnes any thoughts on this suggestion?

**Comment by MarcusBarnes** [comment]
@mjordan Good suggestion and definitely worth exploring as an optimization.  Thank you for the suggestion.

**Comment by mjordan** [comment]
OK,thanks. I'll do up a quick implementation of  this now that I'm troubleshooting the current issue with the Chinese Times job..

**Comment by MarcusBarnes** [comment]
@mjordan Sounds good.  It will be interesting to do some comparisons to help determine if how much of an improvement in speed we see.  Thanks again.

**Comment by mjordan** [comment]
Now that I'm looking at this, we can skip checking for the specific set manipulator and just provide a [FETCHER] option like 'use_cached_records'.

**Comment by mjordan** [comment]
Or even overload the `--limit`` option to allow `--limit=cached`. Too git-like?

**Comment by mjordan** [comment]
Added to the Cdm and Csv fetchers. Syntax is:

`php mik --config=cartoons_config.ini --limit=cached`

@MarcusBarnes you can test this by running an MIK job as usual, then rerunning using the `--limit=cache` option. Only the records that are cached in the FETCHER's temp_directory will be used. Delete the contents of the output directory before running with `--limit=cached`.

**Comment by mjordan** [comment]
@MarcusBarnes I'm not sure how much performance this will boost but it will be useful during debugging and testing since it provides a way of rerunning MIK using the same objects as the previous run used.

**Comment by MarcusBarnes** [comment]
@mjordan This appears to work properly for the CSV toolchain (tested with a small cartoons set).  I'm getting some unexpected behaviour for a test I'm running with the Cdm Newspaper toolchain.

**Comment by mjordan** [comment]
Ok, thanks. I only tested with single file objects from CONTENTdm. Let me take a look.

**Comment by mjordan** [comment]
The glob pattern at https://github.com/MarcusBarnes/mik/blob/issue-144/src/fetchers/Cdm.php#L242 picks the first cached record and passes it back to mik. When mik gets to getChildren(), if the Cdm object corresponding to the cached record doesn't have children, things go south from there. So, looks like reusing this cached metadata works for single-file objects, but not compound. Let me think about this over the weekend.

**Comment by mjordan** [comment]
Just a thought - if reusing cached metadata doesn't give us noticeable performance gains, and the only use case for doing this is testing / debugging, maybe a simple post-write hook that dumps out a list of record keys that can then be reused by the SpecificSet fetcher manipulator gives us the same thing. Would at least work for simple and compound source objects.

**Comment by mjordan** [comment]
@MarcusBarnes I think this issue is obsolete. We are using cached metdata in all fetchers now except Filesystem, where it doesn't really apply. Can I close this and delete the accompanying branch?

**Comment by MarcusBarnes** [comment]
I'm fine with closing this and deleting the accompanying branch.
