### ISSUE TITLE
--checkconfig=all option reports an error for a working Cdm utils_url

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#145]
The checkconfig=all option reports an error for a valid Cdm utils_url:

``Error: The URL [utils_url] (defined in configuration setting utils_url) appears to be a bad URL (response code 200).``

This may be due to the fact that the utils_url is a base URL for the utility URL  and does not return any data without additional URL parts and parameters.

**Comment by mjordan** [comment]
Yes, I was aware of this. Has to do with bad HTTP response codes. I'll investigate.

**Comment by mjordan** [comment]
The problem is that CONTENTdm returns a 404 for that URL. Looks like if we append 'getthumbnail' (e.g., `http://content.lib.sfu.ca/utils/getthumbnail`) we get a proper 200. I'll implement this workaround.

**Comment by mjordan** [comment]
@MarcusBarnes this is ready for testing.

**Comment by MarcusBarnes** [comment]
@mjordan Cool.  I'll test now.  Thanks.

**Comment by MarcusBarnes** [comment]
:thumbsup:

**Comment by MarcusBarnes** [comment]
Closed with the merging of pull-request https://github.com/MarcusBarnes/mik/pull/147.  Thank you @mjordan
