### ISSUE TITLE
Consolidate or Check repeated alias setting in configuration files for Cdm workflows

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#146]
The Cdm alias setting is repeated in various sections of the configuration files for Cdm workflows.  This opens the possibility of human error.  Possible solutions could be consolidating the alias setting under one configuration section or add a check to --checkconfig that will look for repeated settings with the configuration file and confirm that settings repeated under different sections have the same value.

**Comment by mjordan** [comment]
Related issue: #107

**Comment by mjordan** [comment]
I've added a --checkconfig option for this so am closing.
