### ISSUE TITLE
Generalize $record_id in mik

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#15]
[$record_id](https://github.com/MarcusBarnes/mik/blob/master/mik#L56) in the main loop in mik is specific to CONTENTdm records, which are identified by a "pointer". Before we do any additional work on non-CONTENTdm fetchers (like the CSV fetcher), we should remove CONTENTdm-specific naming and logic from mik, and establish a pattern for other record types.

**Comment by MarcusBarnes** [comment]
A first attempt at addressing this issue can be found in commits 2ea22608ab34d720d8de5bb1be7e56b7b8cffd3b and 3697fd7cf675025ad11e6b586274262a31f21b39.

**Comment by mjordan** [comment]
Looks good.
