### ISSUE TITLE
Implement filegetter manipulators in the CdmNewspaper filegetter to allow fine-grained control over source directory list

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#150]
Tests confirm that limiting the specificity of the list of input directories for newspaper master images can increase the time-to-process for newspaper issues substantially. Given the number of possible locations where master images can be stored, it would be very useful to provide a way for implementors to have fine-grained control over the list of input paths.

Currently we don't implement filegetter manipulators in the CdmNewspapers. We have set a pattern for filegetter manipulators in the CdmSingleFile filegetter class that we can follow.

**Comment by mjordan** [comment]
Also going to try adding a static cache to the the directory list.

**Comment by MarcusBarnes** [comment]
Cool.

**Comment by mjordan** [comment]
Just confirmed that using a static cache within getIssueMasterFiles() lets us build the list only once. One optimization down!

**Comment by MarcusBarnes** [comment]
:thumbsup:

**Comment by mjordan** [comment]
I've modified the Cdm newspapers filegetter class to load fetcher manipulators that return true/false value for a given path in `$potentialFilesArray`, and added a fetcher maniplator that has the following [MANIPULATORS] signature:

`filegettermanipulators[] = "FilterCdmNewspaperMasterPaths|out|foo|baz"`

The first parameter is 'in' or 'out' and the remaining paramters are regex patterns. If the first parameter is 'out' paths that match any of the patterns are removed from `$potentialFilesArray` and if the first parameter is 'in', only paths that match any of the patterns are added to `$potentialFilesArray`.

@MarcusBarnes I'd like you to test if you can by:

1. Adding a few fake paths below the input directories for a newspaper (make sure they end in files with the '.tif' extension) and enabling the new FilterCdmNewspaperMasterPaths manipulator to filter out those test paths and
2. Defining your input directory in a job to be one lever higher than the real input directory and registering FilterCdmNewspaperMasterPaths to filter in paths that match your real input directory.

Your manipulator log will record what has been filtered in our out.

**Comment by mjordan** [comment]
We may want to add this fillegetter manipulator to the CDM book toolchain too.

**Comment by MarcusBarnes** [comment]
@mjordan Unfortunately, my local tests are not giving me expected results.  I'm going to see if I can get things fixed up tomorrow.  Are you OK with me pushing changes to this feature branch or would you like me to make a separate branch?

**Comment by mjordan** [comment]
Keep any changes in that branch. Perhaps my testing instructions weren't clear or complete?

**Comment by mjordan** [comment]
@MarcusBarnes outstanding work in the cdmnewspaper_optimization branch. This gives us a huge performance improvement and is much more robust than my work in the issue-150 branch. I'm willing to close this ticket for now and abandon my work there. We can reexamine adding filegetter manipulators later when the dust settles.

I've tested the changes in the cdmnewspaper_optimization branch to my satisfaction and have merged them into master.
