### ISSUE TITLE
Add a CDM fetcher manipulator that filters on date of object creation

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#151]
Each record returned by CONTENTdm has a 'dmcreated' field with  a value in yyyy-mm-dd format. It will be useful to be able to filter a fetch based on this value. One use case is to fetch all the objects that have been added to a Cdm collection after a specific date.

**Comment by mjordan** [comment]
Pushed to master. Wiki page is at https://github.com/MarcusBarnes/mik/wiki/Fetcher-manipulator:-CdmByDmDate.

**Comment by MarcusBarnes** [comment]
@mjordan Very cool.  Thanks so much.
