### ISSUE TITLE
Missing thumbnail at the issue level for newspapers

### ISSUE THREAD

**Issue by kbolko** [MarcusBarnes/mik#152]
Newspaper issues are currently missing an issue level thumbnail when a package is generated.  Reusing the thumbnail, TN.jpg, from the first available page and placing it in the root of the issue's package works when test manually.

Simplest place to check that the issue level thumbnail shows up is when doing an Islandora Simple Search.

**Comment by MarcusBarnes** [comment]
@kbolko Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/154  @mjordan would you test and merge as appropriate?

**Comment by mjordan** [comment]
Tested and merged. Thanks @kbolko and @MarcusBarnes.
