### ISSUE TITLE
CdmSingleFile filegetter can no longer create packages that don't have masters on local filesystem

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#155]
It appears I was overzealous in my fix for #85. Looking at the source code of the CdmSingleFile writer I think it would be much simpler to just set `[FILE_GETTER] input_directories[]` to false to have MIK get the file associated with the object from CONTENTdm than to use the byzantine logic that we have now.

**Comment by mjordan** [comment]
Fixed. If `[FILE_GETTER] input_directories` is set to an array like this:

`input_directories[] = "/home/mark/Downloads/punk_poster_tiffs"`

MIK looks for masters in the designated directories, in conjunction with the CdmSingleFile filegetter manipulator. If `[FILE_GETTER] input_directories` is commented out, not present, or is is set to false like this:

`input_directories = false`

(note that it is not an array) MIK gets the file from CONTENTdm.

@MarcusBarnes if you can test I would appreciate it. Let me know if you need configs for testing.

**Comment by mjordan** [comment]
Here is the documentation on this toolchain: https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CONTENTdm-single-file-objects.

**Comment by MarcusBarnes** [comment]
Thank you @mjordan. I'll test and get back to you about how things go.

**Comment by MarcusBarnes** [comment]
@mjordan I've tested the changes and they function as expected.

**Comment by mjordan** [comment]
Merged with https://github.com/MarcusBarnes/mik/pull/157.
