### ISSUE TITLE
Remove src/filegetters/Cdm.php

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#16]
We should remove src/filegetters/Cdm.php if it is not being used.

**Comment by MarcusBarnes** [comment]
src/filegetters/Cdm.php has been removed.  See b53d4ece5e083dff475cdc4ab4fcdce505a7ec74.  Note that much of what was in src/filegetters/Cdm.php was rolled into the more appropriately named src/filegetters/CdmNewspapers.php class.
