### ISSUE TITLE
remove_files.php contains a typo

### ISSUE THREAD

**Issue by kbolko** [MarcusBarnes/mik#160]
`.Thumbs.db` is not the file you are looking for, the file you are looking for is `Thumbs.db`.

On line 18 replace,
'.Thumbs.db',
with
'Thumbs.db',

Tested and now removes Thumbs.db files.

**Comment by mjordan** [comment]
@kbolko  Are you sure that there aren't hidden (.) versions of this filename? I'm pretty sure I've seen them. I'd rather just add both versions of the filename to the list.

**Comment by kbolko** [comment]
@mjordan I'm sure.  You can take a look at the wiki page [https://en.wikipedia.org/wiki/Windows_thumbnail_cache](url).

**Comment by mjordan** [comment]
OK, fixed and closed.
