### ISSUE TITLE
Running checks on CSV toolchain should not report URLs and CONTENTdm aliases

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#163]
Running mik with --checkconfig=all on a CSV .ini file produces the following:

```
Mapping snippets are OK
Paths are OK
URLs are OK
CONTENTdm aliases are OK
```
We should not be checking or reporting on URLs or CONTETNdm aliases, since the CSV toolchains use neither.

**Comment by mjordan** [comment]
@MarcusBarnes can you test and merge at your convenience? I've modified only src/config/Config.php so there should be no conflicts with the fix for #168.

Running `--checkconfig=all` on a CONTENTdm toolchain .ini should produce:

```
php mik --config=vanpunk.ini --checkconfig=all
Commencing MIK.
Mapping snippets are OK
Paths are OK
URLs are OK
CONTENTdm aliases are OK
```

whereas running it on a CSV toolchain .ini should produce

```
php mik --config==tutorial_config.ini --checkconfig=all
Commencing MIK.
Mapping snippets are OK
Paths are OK
```

**Comment by MarcusBarnes** [comment]
@mjordan Worked as expected in my local tests.

**Comment by MarcusBarnes** [comment]
Addressed with commit https://github.com/MarcusBarnes/mik/commit/62fd9b5cf38543bc24b763f2d9e352a16e0fb0c9
