### ISSUE TITLE
Add checks to validate CSV metadata file

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#164]
It would be useful to provide a check for the CSV metadata file and report its column headings and how many records it contains. It would also be useful to catch this error:

`Fatal error: Uncaught exception 'InvalidArgumentException' with message 'The array must contain unique values' in /mik//vendor/league/csv/src/Reader.php:249`

and report if it occurs. This error is triggered in the CSV fetcher's getRecords() method, but the reader's ->fetchAssoc() method if the CSV file contains empty columns headers, for example, although that is not the only condition that will trigger it.

**Comment by mjordan** [comment]
Added checks for column header uniqueness and emptiness, and check to make sure the all rows have same number of columns as header row. The tests on the header row will detect the condition that throws the error documented above.

Branch issue-164 was created from issue-163, so it should be merged into master after issue-163 is.

**Comment by mjordan** [comment]
@MarcusBarnes just noticed that we hadn't merged in the issue-163 and issue-164 branches. Want me to see if they still merge cleanly?

**Comment by MarcusBarnes** [comment]
@mjordan Yes please.  Thank you.

**Comment by mjordan** [comment]
issue-163 branch was merged into master, issue-164 was not. There are now conflicts, which I will resolve and test.

**Comment by mjordan** [comment]
OK, have fixed conflicts and committed fix to issue-164 branch. Will test this evening and report back, so we can merge into master and close this issue.

**Comment by mjordan** [comment]
@MarcusBarnes I've completely and profoundly screwed up the issue-164 branch. Reminder to self to not drive a vehicle, operate heavy machinery, or use git when tired. I can salvage the code that does the validation of the CSV file but I'm going to delete it and start from a fresh branch from master if that's OK with you.

**Comment by MarcusBarnes** [comment]
@mjordan That's OK with me.  Thank you for your efforts.

**Comment by mjordan** [comment]
OK, done. All PHPUnit tests pass. If you want to smoketest (I don't think it's necessary), take the tutorial CSV file and add a column header to the end of the first row, then run `./mik -c tutorial_config.ini -cc csv`.

In either case I can create a PR.

**Comment by mjordan** [comment]
@MarcusBarnes Any objections to me merging the issue-164 branch into master?

**Comment by MarcusBarnes** [comment]
We can merge.  Thank you.

**Comment by mjordan** [comment]
Done.
