### ISSUE TITLE
Add a sleep option

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#168]
In some cases, it might be preferable to slow down MIK so that it puts less demand on the CONTENTdm server, local disk, etc.

**Comment by mjordan** [comment]
@MarcusBarnes can you test the issue-168 branch and merge at your convenience?

Adding `sleep = 5` to the [FETCHER] section of the .ini file will cause MIK to pause for 5 seconds before processing the next object. If the `sleep` option is absent there should be no side effects.

**Comment by MarcusBarnes** [comment]
@mjordan Thanks - will do.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you - this appears to function as expected.

**Comment by mjordan** [comment]
Great, thanks - merge at your convenience and I'll document it on the toolchain wiki pages.

**Comment by MarcusBarnes** [comment]
Closed with commit https://github.com/MarcusBarnes/mik/commit/6204b783f2a63471b7e9751943f8546fecc03651  Thank you @mjordan for your contribution.
