### ISSUE TITLE
getChildrenPointers() shold be getChildren()

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#17]
https://github.com/MarcusBarnes/mik/blob/master/mik#L73 : getChildrenPointers() and source function at https://github.com/MarcusBarnes/mik/blob/master/src/filegetters/CdmNewspapers.php#L88 should not contain CONTENTdm-specific language. getChildren() is more generic.

**Comment by MarcusBarnes** [comment]
Addressed in commit 5e9b9dda5d9732d23e0b68c5a6948a14d68eccbe.
