### ISSUE TITLE
check_files.php tries to access OCR.txt even if you don't check for it

### ISSUE THREAD

**Issue by kbolko** [MarcusBarnes/mik#178]
Appears to be missing and IF statement near line 198

                    // Check each OCR.txt file to ensure it's encoded in UTF-8.
                    $path_to_ocr_file = $page_dir . DIRECTORY_SEPARATOR . 'OCR.txt';
                    $ocr_content = file_get_contents($path_to_ocr_file);
                    if (!mb_check_encoding($ocr_content, 'UTF-8')) {
                        error_log("$path_to_ocr_file is not valid UTF-8\n", 3, $options['log']);
                        $bad_ocr_encoding  = true;

**Comment by mjordan** [comment]
I'll push a fix shortly.

**Comment by mjordan** [comment]
@kbolko can you confirm that this works?

**Comment by kbolko** [comment]
@mjordan The fix appears to resolve the issues.
