### ISSUE TITLE
CdmToMods Metadataparser:  If %value% replacement text which contains $

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#181]
The CdmToMods Metadataparser uses the preg_replace function to replace the Cdm metadata into the MODS metadata mapping snippet.  Should the replacement value contain a substring such as $1.95 - these may be interpreted with special meaning and removed from the output.  See this comment on the PHP docs for example: http://us1.php.net/manual/en/function.preg-replace.php#103985

Since we are using the convention of using %value% slug in the metadata mapping to indicate where to place replacement text, we can use str_replace function rather than preg_replace to help avoid the above problem and similar issues.

**Comment by MarcusBarnes** [comment]
@mjordan I have a fix for this issue in the following pull request: https://github.com/MarcusBarnes/mik/pull/182  Please merge if you are satisfied with the fix.  Thank you.

**Comment by mjordan** [comment]
Nice work @MarcusBarnes, testing looks good so I've merged this fix.
