### ISSUE TITLE
Validate the values of --checkconfig, and validate the options users are allowed to pass to mik

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#183]
If the user provides a value to `--checkconfig` that is not expected, mik will execute as if `--checkconfig` was not provided. Also, we should restrict allowed options to mik to only `--config`, `--limit`, and `--checkconfig`.

**Comment by mjordan** [comment]
I've addressed invalid values for `--checkconfig` but it looks like checking for MIK options other than the allowed ones is a bit more challenging. Will continue work later today.

**Comment by mjordan** [comment]
@MarcusBarnes would you mind testing this work so far so we can merge it? I don't know when I will have time to complete it but what I have done so far is useful. To test, in the issue-183 branch, run MIK with the `--checkconfig` option as you normally would to make sure there are no side effects. Then, run MIK with an invalid value for `--checkconfig`. It should tell you that your value is not allowed.

**Comment by MarcusBarnes** [comment]
@mjordan Thanks.  I'll test.

**Comment by MarcusBarnes** [comment]
@mjordan Works as expected. I will issue a pull-request and merge momentarily.  Thank you for your contribution.

**Comment by MarcusBarnes** [comment]
Closed with commit 979cfa4d1861f9de78836b905ff13b84a1fe55bc.
