### ISSUE TITLE
Mismatches in metadata mappings CONTENTdm to MODS metadata parser results in a broken log message

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#185]
In the CONTENTdm to MODS metadata parser, mismatches in the metadata mappings file produce log messages like `Mappings file contains a row $CONTENTdmField that`; in the CSV to MODS parser, "is not in source CONTENTdm metadata for this object." is appended to the message.

I've smoke tested this and it works so committing it directly to master.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.
