### ISSUE TITLE
Add desktop notifications that MIK jobs are complete

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#188]
Using this cool component: https://github.com/jolicode/JoliNotif.

**Comment by MarcusBarnes** [comment]
:+1:

**Comment by mjordan** [comment]
Tested on Ubunutu and Win7. On Win7, MIK doesn't exit until you close the notification. Works as expected otherwise. @MarcusBarnes can you test on OS X?

**Comment by MarcusBarnes** [comment]
@mjordan Cool!  I'll test tomorrow when I'm next at my development machine.  Thank you.

**Comment by mjordan** [comment]
Thanks. Just added some logic to allow you to not send the notification, e.g., if you're using MIK in a scripted workflow. Couldn't think of a better place to add the option, so I used `[WRITER][notification] = true`. If `[WRITER][notification]` is absent, or if it is set to `false`, the notification is not sent.

**Comment by MarcusBarnes** [comment]
@mjordan My first go at testing on my development machine (Mac using bash terminal) didn't appear to work as expected.

**Comment by MarcusBarnes** [comment]
@mjordan Please feel free to close issues that you think are no longer needed.   We can always reopen issues should there be enough feedback to do so.  Thanks!
