### ISSUE TITLE
Make fetchers/Fetcher.php an abstract class

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#19]
Refactor fetachers/Fetcher.php as an abstract class to be extended by particular instances (such as fetchers/Cdm.php or fetchers/Csv.php).  In particular, be sure to include versions of the getItemInfo() and queryTotalRec() methods to force extending classes to define these methods.

PHP Abstract Class documentation: http://php.net/manual/en/language.oop5.abstract.php

After successfully completing this task, review other sections of MIK where a similar abstraction of the parent classes makes sense and create ToDo issues for the tasks.

**Comment by mjordan** [comment]
Great minds think alike... I was just reading up on abstract classes myself since they seemed to be a good fit for what we're doing.

**Comment by MarcusBarnes** [comment]
Yes - thank you. It seems appropriate to create at least one abstract class for each major section of MIK: fetchers, metadata_parser, file_getter, writer, file_manipulators,  and metadata_manipulators.

**Comment by mjordan** [comment]
:+1: .

**Comment by MarcusBarnes** [comment]
Initial work on this issue is addressed in commit d30da9319964bc68d908855f86931972c6e262fe.   For further refinements and modifications, please create separate issues.
