### ISSUE TITLE
Use "Page x" for book page titles

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#191]
CONTENTdm Book toolchain should create page-level MODS files that generate the following MODS:

```xml
  <titleInfo>
    <title>Page 4</title>
  </titleInfo>
```

This is consistent with how the CONTENTdm newspaper toolchine works.

**Comment by MarcusBarnes** [comment]
@mjordan Addressed in feature branch https://github.com/MarcusBarnes/mik/tree/issue-191.  Please test when you have a moment.

**Comment by mjordan** [comment]
Looks good @MarcusBarnes, thanks for fixing. I'll merge into master and delete this branch.
