### ISSUE TITLE
Trailing whitespace at the end of mappings rows causes XML creation errors

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#192]
These errors can be hard to track down. Trimming this whitespace eliminates the errors.

**Comment by mjordan** [comment]
@MarcusBarnes this was a trivial change, but I tested thoroughly before I merged.

**Comment by MarcusBarnes** [comment]
Thank you @mjordan.  Great catch.

**Comment by mjordan** [comment]
Been spending a lot of time with mappings files past few days!
