### ISSUE TITLE
Allow comments and commented out rows in mappings files

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#194]
It would be very useful to allow comments in mappings files, and to be able to comment out rows while troubleshooting mappings issues. I propose that we use the double forward slash (`//``) to indicate that a line is to be skipped.

**Comment by mjordan** [comment]
On second thought, maybe we should use `#` like we do in the [Specific Set](https://github.com/MarcusBarnes/mik/wiki/Fetcher-manipulator:-SpecificSet) manipulator. I think it's a pretty safe bet that it wouldn't occur as the first character in any field labels.

**Comment by mjordan** [comment]
Added to both CdmToMods.php and CsvToMods.php. To test, check out the issue-194 branch, add a `#` as the very first character in a row in the mappings file, run MIK, and inspect the resulting MODS. The element that was mapped in the commented-out row should be absent from the MODS.

@MarcusBarnes can you test and merge into master if you see no problems?

**Comment by MarcusBarnes** [comment]
@mjordan Tested using both CdmToMods.php (using the Newspaper toolchain) and CsvToMods.php (using the CsvSingleFile toolchain).  Works as expected.  I'll merge into master momentarily.  Thank you for your contribution.

**Comment by mjordan** [comment]
Thanks!

**Comment by MarcusBarnes** [comment]
Closed with commit https://github.com/MarcusBarnes/mik/commit/c3b30c8fb80ec01a6103150315e284e8f785dd01.
