### ISSUE TITLE
Document skip_obj setting in Wiki

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#207]
Assuming the the issue-206 branch is merged into master, document the skip_obj WRITER setting in the wiki documentation for the CdmBook toolchain (and any other toolchains it becomes used).

**Comment by mjordan** [comment]
@MarcusBarnes I'm not seeing an issue-206 branch. DId you push it up?

**Comment by MarcusBarnes** [comment]
@mjordan After reviewing it again, I merged the pull request.  The changes are in master.    The changes are documented in: https://github.com/MarcusBarnes/mik/issues/206.

**Comment by mjordan** [comment]
@MarcusBarnes thanks very much, I'll document on wiki and close this issue.

**Comment by mjordan** [comment]
Catching up on this one late - https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Generating-OBJ-datastreams-for-book-and-newspaper-pages-if-you-have-no-master-files
