### ISSUE TITLE
Fail more gracefully if unable to access directories from config input_directories

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#22]
Fail gracefully with a message that will make more sense to general users should mik be unable to access directories in the configuration FILE_GETTER input_directories[].  This may happen if one fails to connect to input_directories from a network drive or if the user makes a mistake when providing the input directory path.  Currently, mik will issue a fatal error that may cause unnecessary confusion among certain users.

More generally, identify other places where mik should fail gracefully, creating new issues to help track these.

**Comment by mjordan** [comment]
Mitigated to some extent (for configuration typos anyway) by resolution of #43.

**Comment by mjordan** [comment]
I wonder if we can close this since we now have the ability to check the existence of directories named in config files.

**Comment by MarcusBarnes** [comment]
The config check should deal with most cases where this may happen for general users, especially when first starting MIK.  We will want to deal gracefully  situations where directories become unavailable. for example, during a temporary network malfunction,  but we can do this using the proposed exception class https://github.com/MarcusBarnes/mik/issues/50 .  The idea being that MIK will log such situations and continue processing packages if possible.

Let's close this issue since it has been mitigated by the resolution of https://github.com/MarcusBarnes/mik/issues/43 and more complicated situations can dealt with once https://github.com/MarcusBarnes/mik/issues/50 is resolved.  

Thank you @mjordan for your work on https://github.com/MarcusBarnes/mik/issues/43 and your continued input - much appreciated.
