### ISSUE TITLE
src/writers/CdmPhpDocuments.php should be named CdmPdfDocuments.php

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#223]
This filename and classname is obviously the result of fatigue: https://github.com/MarcusBarnes/mik/blob/master/src/writers/CdmPhpDocuments.php

This should be renamed to match what it does: generates PDF files.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/320 (merged with commit https://github.com/MarcusBarnes/mik/commit/3613a3d5ae49a6828d278a4171ce4b2575fa7e4a).
