### ISSUE TITLE
Add extras script that fixes back JP2 files from CONTENTdm

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#224]
Some .jp2 files generated by CONTENTdm do not work in Islandora, they are completely black. The files are valid JPEG2000 files, they just don't work with Islandora. Running them through IM's `convert` command fixes them, but increases their size considerably.

Write a script that recurses down a directory of ingest packages and fix all the JP2s.

**Comment by mjordan** [comment]
extras/scripts/fixjp2s.php added.

**Comment by MarcusBarnes** [comment]
👍
