### ISSUE TITLE
Modify --checkconfig to allow toolchains that don't use mapping files

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#228]
Follow up from #142. The new OAI-PMH, and possibly other future toolchains, don't use mapping files, so we need to add logic to checkconfig to allow this.

**Comment by mjordan** [comment]
Fixed in the issue-228 branch. Also added a new function, `checkOaiEndpoint()`, that determines if the ['FETCHER']['oai_endpoint'] value returns a Guzzle `RequestException` or not.

Test by running `mik --config=oaiconfig.ini --checkconfig=all`. There should be no message about snippets (the check is skipped for this toolchain) and if the OAI-PMH endpoint is OK, the 'URLs are OK' message should appear; if not, an error message indicating that the OAI endpoint appears to be invalid will appear.

**Comment by MarcusBarnes** [comment]
@mjordan Tested and works as expected.

Since this workflow does not expect input_directories, the message "No input directories are defined in the FILE_GETTER section." appears when using `--checkconfig=all`.  Would this cause some confusion for less experienced MIK users?

**Comment by MarcusBarnes** [comment]
@mjordan Please feel free to close this issue and create a pull-request.

**Comment by mjordan** [comment]
@MarcusBarnes yes, I thought about that. Let me wrap the check for input directories in the same sort of logic that the check for mappings files is in.

Thanks for testing.

**Comment by MarcusBarnes** [comment]
@mjordan You're welcome.

**Comment by mjordan** [comment]
@MarcusBarnes I've added FILE_GETTER-specific logic to checkInputDirectories(), and done a bit of cleanup around making this work better. I am beginning to think that there are so many toolchain-specific options that it's getting challenging to have the checkconfig code offer informative messages  to end users.

If you wouldn't mind giving this a quick smoke test by commenting out the [FETCHER][input_directory] (for Csv toolchains) and [FETCHER][input_directories] (for Cdm toolchains) values and running checkconfig, that would be great. Unless you see further problems, feel free to merge.

**Comment by MarcusBarnes** [comment]
@mjordan Thanks.  I will test.

I was thinking that there are "classes" of workflows and part of creating a new workflow would be selecting which configuration class matches the workflow (and if there is no match to existing configurations, create a new one or extend the existing Config class).  I would have to think about how we'd implement this since the Config class loads the configuration file.  Perhaps a new MIK command line option?

**Comment by mjordan** [comment]
Interesting idea. Makes me think about how we could automate MIK jobs (which is something we will certainly want to do). Quite a while ago we had talked about "preflight" hooks that work similar to the existing post-write hooks but that would be more suited to input data validation or preprocessing. Perhaps a workflow configuration framework could incorporate this as well.

**Comment by MarcusBarnes** [comment]
@mjordan Tested and worked as expected.

**Comment by MarcusBarnes** [comment]
Addressed in commit c21194680182f0f92e3cdac1eeadaedb130fda9e.  Thank you @mjordan for your contribution.  We can continue the conversation regarding the ideas in https://github.com/MarcusBarnes/mik/issues/228#issuecomment-231263589 and https://github.com/MarcusBarnes/mik/issues/228#issuecomment-231244927 in other issues or elsewhere.  Thank you again.
