### ISSUE TITLE
Provide a file getter for the OAI-PMH toolchain that gets the URL for the PDF, etc. from a field in the Dublin Core

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#231]
Some OAI-PMH compliant platforms follow a convention where they put the direct link to the PDF or other payload file in a specific field in the OAI Dublin Core. For example, BePress' [Digital Commons platform](http://digitalcommons.bepress.com/cgi/viewcontent.cgi?article=1087&context=reference) puts it in the second `<dc:identifier>` element. The [RIOXX Application Profile](http://www.rioxx.net/profiles/v2-0-final/) also specificies that the sole dc:identifier must contain a URL to the resource.

The file getter should provide a configuration option that allows the use of an XPatch expression to get the desired value.

**Comment by mjordan** [comment]
@MarcusBarnes I've pushed up branch issue-231, with documentation at https://github.com/MarcusBarnes/mik/wiki/OAI-PMH-for-repositories-that-identify-resource-files-in-a-record-element. I've only got one OAI-PMH repository to test against, so perhaps there's no need for you to test this toolchain, but if you'd like to test let me know and I'll share the .ini file with you.

**Comment by mjordan** [comment]
@MarcusBarnes I'm happy to have this branch merged into master without any testing since it's somewhat experimental anyway. Unless you object, I can merge it and link its wiki page from the MIK homepage.

**Comment by MarcusBarnes** [comment]
@mjordan Would you please create a pull-request?  I'll double check the modified files and if it's just the new class files for the workflow I'll merge.  Thank you for this work!

**Comment by mjordan** [comment]
Will do.

**Comment by MarcusBarnes** [comment]
Closed with commit 44a78c7b60d9fd893de744e4a25f374cddd8f05a.  Thank you @mjordan for the initial work on this tool chain.

**Comment by mjordan** [comment]
Sweet - I'll update the MIK README to mention this new toolchain after testing on the CSV Compound branch is done. Thanks!
