### ISSUE TITLE
Add end-to-end tests for CSV toolchains

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#238]
Currently, we only have PHPUnit tests for the CSV single-file fetcher. We should add tests for all  of the CSV toolchains that test filegetters and writers as well.

**Comment by mjordan** [comment]
@MarcusBarnes I've written an end-to-end test for the CsvToJson toolchain, which writes out a single package and then tests the value of a field in the JSON and also tests for the existence of the JPG file. It's in `tests/CsvToJsonToolchainTest.php` if you want to take a look, specifically the `testWritePackages()` function.

I'll move on to write equivalent tests for all of the CSV toolchains.

**Comment by MarcusBarnes** [comment]
@mjordan Awesome. Thank you.

**Comment by mjordan** [comment]
@MarcusBarnes we how have end-to-end tests for all but the CSV compound object toolchain, which I will add later. I had to name two of the test files with a leading 'X' so that they get executed after the other two; see my comment at the tops of each file. All four CSV toolchain test files pass PRS2 code checks. All you have to do to test these tests (:smile:) is run 

```phpunit --exclude-group FITS --bootstrap vendor/autoload.php test```

in the issue-238 branch. Once you test, I'll open a PR.

**Comment by mjordan** [comment]
@MarcusBarnes I'm working on the compound tests now, will push to the issue-238 branch when they're done.

**Comment by mjordan** [comment]
@MarcusBarnes I've added a test file for the CsvCompound toolchain, but have encountered more strangeness within the test environment. In a nutshell, the creation of child-specific MODS is failing during tests but works as expected when run outside of the test environment. Therefore the tests for this toolchain are incomplete. I'll open a separate issue for this latest behaviour. Please test as above and merge when you have time.

**Comment by MarcusBarnes** [comment]
Closed with merging of pull-request https://github.com/MarcusBarnes/mik/pull/280 (commit https://github.com/MarcusBarnes/mik/commit/0d9862aa0a5abf2c54c5e14feecaed7446be15b5).
