### ISSUE TITLE
Document simplify mappings file usage

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#24]
Document the simplified mappings file structure from https://github.com/MarcusBarnes/mik/issues/7 in the project wiki and or the developer README.  Give examples on usage for CONTENTdm and other data sources as appropriate.

**Comment by mjordan** [comment]
Started in https://github.com/MarcusBarnes/mik/wiki.

**Comment by mjordan** [comment]
Largely done in the wiki.
