### ISSUE TITLE
Create metadata manipulator that allows simple regular expression subsititions on specific MODS fields

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#242]
Use case is to replace "Page x" in CONTENTdm child objects with "Part x".

**Comment by mjordan** [comment]
First version tested on a batch of compound objects that had 'Page' in their MODS `<title>` elements that needed to be replaced with 'Part'. Uses the following signature in .ini files:

`metadatamanipulators[] = "SimpleReplace|/pattern/|replacement text"`

e.g. in my use case:

`metadatamanipulators[] = "SimpleReplace|/<title>Page/|<title>Part"`

Will write up wiki entry on how to use it.

**Comment by mjordan** [comment]
Wiki entry is at https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-SimpleReplace.

**Comment by mjordan** [comment]
@MarcusBarnes I've documented a few complex patterns and tested this new manipulator in CONTENTdm and CSV MODS toolchains and it works as expected. Unless you want to do additional testing, please merge the issue 242 branch into master at your convenience.

**Comment by MarcusBarnes** [comment]
@mjordan Awesome stuff.  Thank you for testing.   Since the issue-242 branch only adds the manipulator and does not modify other parts of MIK, I'm comfortable merging the code for the new manipulator at this time.  Please create separate issues should problems with the manipulator become apparent.

**Comment by MarcusBarnes** [comment]
Addressed in commit 1dab8c7.

**Comment by mjordan** [comment]
Cool, thanks. In writing the PHPUnit test I noticed that the method we were using to exclude the FITS test wasn't working as intended, so I just pushed a small tweak directly to master, basically just using the command-line option `--exclude-group` to skip that test. It'd documented in README_DEV.md.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.
