### ISSUE TITLE
Add PHPUnit test for FilterModsTopic metadata manipulator, complete its wiki page

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#245]
Wiki page is at https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-FilterModsTopic.

**Comment by mjordan** [comment]
Test passes, wiki page updated.

**Comment by mjordan** [comment]
Can we close this one?

**Comment by MarcusBarnes** [comment]
Closing.  Re-open as necessary.  Thanks @mjordan for your contribution.

**Comment by mjordan** [comment]
@MarcusBarnes it appears that the issue-245 branch was never merged into master. The new test passes - mind if I merge it?

**Comment by MarcusBarnes** [comment]
Please merge as appropriate.  Thank you.
