### ISSUE TITLE
Update check_files.php expects structre.cpd files, not structure.xml files

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#246]
The Islandora Compound Batch module (still under internal testing) now uses structure.xml as the filename for its structure files.

**Comment by mjordan** [comment]
@MarcusBarnes I've tested this and it works as expected, I don't see a need for additional testing the issue-246 branch before merging into master if you don't.

**Comment by MarcusBarnes** [comment]
Merged into master via pull-request https://github.com/MarcusBarnes/mik/pull/247 in commit 1f8792e .
