### ISSUE TITLE
Review and clean up Mods and CdmToMods classes 

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#25]
Remove duplicated code and other cruft in [Mods](https://github.com/MarcusBarnes/mik/blob/master/src/metadataparsers/mods/Mods.php) class that should only be in the child [CdmToMods](https://github.com/MarcusBarnes/mik/blob/master/src/metadataparsers/mods/CdmToMods.php) class.

Rename methods in the Mods parent class so that they are more generic, removing specific references to CONTENTdm.

**Comment by MarcusBarnes** [comment]
Some initial work on this issue in commits 4e35c1a3b1d37a9c40ba7b66c9ef1ec6ea098422 and dd4aaeb323886b9f711c31abf878e7142f082f2f.

**Comment by MarcusBarnes** [comment]
Additional clean up in c16af2b0c7f244a7890f6a1a0ae763335028ff57, e4d0af6ef50d17edded889f36000636cf5a01919, ce4ee54a58d36e4e065d70f48e6a6805329f06ee.

**Comment by mjordan** [comment]
Also related - #40 and #365.

**Comment by mjordan** [comment]
Addressed for now in #405, so closing.
