### ISSUE TITLE
Add the [WRITER] datastreams[] option to the OAI toolchain

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#257]
Would be very useful to testing, etc. as it has proven to be in other toolchains.

**Comment by mjordan** [comment]
This toolchain could write out DC, MODS, ETDMS, or any other metadata format, depending on the OAI metadata specified in the `[FETCHER] metadata_prefix` option. Perhaps valid options for `datastreams[]` for this toolchain should be none (i.e. produce all datastreams), 'OBJ', and 'OAI', the latter standing for whatever is specificed in `[FETCHER] metadata_prefix`.

**Comment by mjordan** [comment]
Talked to @bondjimbond about this today and we agreed that the intent of this feature is to be able to only get the metadata from the remote OAI repo, not to determine which datastreams are processed. I had originally use `datastreams[]` because in the CONTENTdm and CSV toolchains, you  use `datastreams[] = MODS` to achieve the same outcome.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/369 (merged with commit https://github.com/MarcusBarnes/mik/commit/d6ff97fd57d8ec927d56eb330de526e1d4ae0ca7).
