### ISSUE TITLE
Move the saxon/images directory under extras/lsu

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#262]
@jpeak5 would you have any objections if we moved the saxon/images under extras/lsu? We're doing some cleanup/documentation/test addtion/example adding and I'm thinking that we want to keep the top-level MIK directory on the lean side. I can take complete the task.

**Comment by jpeak5** [comment]
Mark, please do feel free to clean up as you see fit.!


- jrp

________________________________

**Comment by mjordan** [comment]
@jpeak5 no problem, we appreciate your work on MIK!

**Comment by mjordan** [comment]
Looking at this a bit more closely, I'd like to propose:

1. `renaming extras/scripts/postwritehooks/apply_xslt.php to` to `extras/scripts/postwritehooks/apply_xslt_with_saxon.php`
1. moving `extras/scripts/xslt-postwrite.md` to `extras/scripts/postwritehooks/apply_xslt_with_saxon.md`
1. moving `saxon/images/tree.png` to `extras/lsu/tree.png`

Plus updating all internal references to the new paths. As above, I can do the work. Any objections?

**Comment by MarcusBarnes** [comment]
@mjordan No objections from me.  Thank you for the suggestion.

**Comment by jpeak5** [comment]
No objections here!

Sent from my iPhone

On Oct 29, 2016, at 5:21 PM, Marcus Emmanuel Barnes <notifications@github.com<mailto:notifications@github.com>> wrote:


@mjordan<https://github.com/mjordan> No objections from me. Thank you for the suggestion.

-

**Comment by mjordan** [comment]
Done!
