### ISSUE TITLE
Provide a metadata manipulator that will allow mapping of multiple source fields to a single MODS snippet

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#263]
MIK mappings for CONTENTdm and CSV toolchains assume a 1-to-1 relationship between the input metadata field and the output snippets. A use case for mapping multiple source fields to one snippet is provided in [this post](https://groups.google.com/d/msg/islandora/QjkAWUn42ls/ukGM_GitBgAJ) to the Islandora user group.

We can use [Twig](http://twig.sensiolabs.org/) templates to allow implementers to construct arbitrarily complex MODS snippets using whatever source fields they want.

**Comment by mjordan** [comment]
Branch issue-263 contains a working implementation. Needs to be documented (I'll move on to that next), but Twig templates have access to all the source metadata for an object, which can then be inserted into the templates using a standard syntax.

Since this branch adds Twig as a component, to test, you need to run `composer update`.

**Comment by mjordan** [comment]
@MarcusBarnes you will notice that in this branch I have modified the Cdm and Csv MODS metadata parsers by adding a `->fieldName` property to the metadatamanipulator objects that are instantiated in the parsers ([example](https://github.com/MarcusBarnes/mik/compare/issue-263?expand=1#diff-b5cce51d895812a35debd83b31917a66R448)). This has no side effects and will let us perform more efficient logic within manipulators ([example](https://github.com/MarcusBarnes/mik/compare/issue-263?expand=1#diff-4a9ed4a43ab5554b78c2d2dff697ea2bR52)). Please let me know your thoughts on this change.

**Comment by mjordan** [comment]
Documentation for this manipulator is at https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-InsertXmlFromTemplate.

**Comment by mjordan** [comment]
To test:

* in the MIK directory, `git fetch`
* `git checkout issue-263`
* `composer update`
* [add an entry to your .ini file's MANIPULATORS section as documented in the wiki page]
  * make sure the field you identify in the entry is present in your mappings file
* [create a Twig template for the MODS you want to generate, using either CSV column headings or CONTENTdm field nicknames as the variables within the template]
  * make sure the path to the template matches the one configured in your .ini file
* run mik.

**Comment by patdunlavey** [comment]
This looks like a great solution. Thanks so much for jumping on this!

I'll test this over the next day or so and let you know how it goes.

**Comment by patdunlavey** [comment]
One thing I want to look into is if it can interact constructively with other metadata manipulators. Here's a possible thought; if instead of putting "{{ some_field }}" in the template, I put in "%value%", then a subsequent manipulator targeting "some_field" could take the output of this manipulator as its input snippet and perform its normal operation on that value.

**Comment by mjordan** [comment]
@patdunlavey currently, each field in the incoming CSV and CONTENTdm metadata is passed through every registered metadata manipulator, which means that a value can be acted on by more than one manipulator. So the process you describe of have more than one manipulator act on a value should be working already. 

However, the tricky part is controlling (or predicting) the order in which the fields are processed and the metadata manipulators fire. Within manipulators, you can implement specific logic to inspect the value of the current element, and (starting with this new manipulator) check to see what the source field's name is. There is no generalized way of doing this though; what I am describing would require some custom, hard-coded metadata manipulators.

Is what you're describing be rephrased as a generalized mechanism to "chain" metadata manipulators together in a specific order to each subsequent on acts on its direct predecessor's output?

**Comment by patdunlavey** [comment]
@mjordan I'm thinking this may just be a special-case documentation task. Unless I'm mistaken, the nature of the InsertXmlFromTemplate manipulator presents the possibility of having more than one manipulator operating on the same field, by first having it run, leaving "%value%" in its output, so that another manipulator can run on its output, as though it was the original snippet coded in the mapping file with "%value%" as the target of the manipulation.

**Comment by mjordan** [comment]
> the InsertXmlFromTemplate manipulator presents the possibility of having more than one manipulator operating on the same field, by first having it run, leaving "%value%" in its output, so that another manipulator can run on its output, as though it was the original snippet coded in the mapping file with "%value%" as the target of the manipulation.

Yes, if you run InsertXmlFromTemplate first, its output should be available to subsequent metadata manipulators, just like any other metadata manipulator.

> As for the firing sequence, am I right that the manipulators will fire in their sequence in the .ini file for each field in the mapping, starting with the first? In that case, we can know that our target field has been manipulated previously.

That's correct - they fire in the same order they appear in in the .ini file.

I will document that the metadata manipulators run in the order in which they appear in the .ini file, and that each metadata value is passed through all manipulators.

One caveat to this however: in the [second comment](https://github.com/MarcusBarnes/mik/issues/263#issuecomment-257159831) in this issue I mention that I've added a `->fieldName` property to the metadata manipulator object. I did this so that a manipulator can *avoid* processing each incoming metadata field. The implication of this is that if a metadata manipulator uses this property to selectively act on incoming metadata fields, that manipulator would not act on the output of all preceding manipulators, only on the output of ones that modified the value of the same field. Does that make sense?

**Comment by patdunlavey** [comment]
Re. the ->fieldName property, yes, I think that makes sense.

**Comment by mjordan** [comment]
I've documented the behavior of metadata manipulators on the [manipulators overview page](https://github.com/MarcusBarnes/mik/wiki/Manipulators). Thanks for pointing this deficiency out @patdunlavey.

**Comment by patdunlavey** [comment]
I tested out the [InsertXmlFromTemplate](https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-InsertXmlFromTemplate) manipulator, and it does what I needed perfectly. Is it premature to think about a merge request?

**Comment by mjordan** [comment]
@patdunlavey we generally merge manipulators pretty quickly but in this case I made some changes to the metadata parser classes (the `->fieldName` stuff) so I'd like to get @MarcusBarnes to do some QA and a smoketest before merging. Thanks for reminding me of this use case and for testing! Feel free to open any other issues that come up.

**Comment by mjordan** [comment]
@patdunlavey one more question - is the wiki page for this manipulator reasonably clear and complete?

**Comment by patdunlavey** [comment]
@mjordan Re. the wiki page, I'd offer two comments. 

First, it should be made more clear that the snippet in the mapping file is not actually used - it is replaced in its entirety by the rendered twig template. The example with
```
null3,"<relatedItem></relatedItem>"
```
could be interpreted to mean that a _relatedItem_ is going to wrap the output of this manipulator. Also, might it be more important to demonstrate the case when you are mapping an actual csv field, than the null example?

Second, I did not understand (and still don't understand) the paragraph on dealing with missing elements in the generated xml. I don't know what "default behavior of collapsing top-level wrapper elements" means or how it's related to missing elements.

I'd be willing to take a stab at trying to write a simpletest for this, if that would be useful - though I may need to bug you for some pointers along the way. Would that be helpful? Should that be a separate issue?

**Comment by mjordan** [comment]
@patdunlavey thanks very much for the suggestions on the docs, I'll address them.

Re. a test, we are attempting to write as many tests for metadata manipulators as possible. We're using PHPUnit, not SimpleTest. If you want to add a test for this one to tests/MetadataManipulatorTest.php that would be awesome. Just fork and open an pull request. Note that we use CSV input data for the tests since it's much easier to deal with than input data from CONTENTdm :laughing:.  Don't hesitate to ask questions.

**Comment by patdunlavey** [comment]
Hi @mjordan, I wrote a very simple test https://github.com/patdunlavey/mik/commit/e97045e60cc52f7ba8ea9b729232c3f1e38af1e4?

I have not actually run it! Maybe you could point me to some basic info on how to run these tests? And any review/feedback is very welcome.

**Comment by mjordan** [comment]
@patdunlavey in your mik directory, run

`phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests`

**Comment by mjordan** [comment]
All your code and sample data look good. Nice work!

**Comment by mjordan** [comment]
@patdunlavey just another comment on running the tests. You should see something like:

```
mark@mark-XPS-13-9343:~/Documents/hacking/mik$ phpunit --exclude-group FITS --bootstrap vendor/autoload.php tests
PHPUnit 4.7.5 by Sebastian Bergmann and contributors.

====================================================================================================> 100%
.Filtering 20 records through the RandomSet fetcher manipulator.
====================================================================================================> 100%
.Filtering 20 records through the RangeSet fetcher manipulator.
====================================================================================================> 100%
.Filtering 20 records through the RangeSet fetcher manipulator.
====================================================================================================> 100%
.Filtering 20 records through the RangeSet fetcher manipulator.
====================================================================================================> 100%
.Filtering 20 records through the RangeSet fetcher manipulator.
====================================================================================================> 100%
.Filtering 20 records through the CsvSingleFileByExtension fetcher manipulator.
====================================================================================================> 100%
.Filtering 20 records through the CsvSingleFileByFilename fetcher manipulator.
......

Time: 910 ms, Memory: 15.25Mb

OK (21 tests, 28 assertions)
```

The number of tests and assertions will likely differ for you since you're running an additional test, but I wanted to tell you that the "Filtering...." output and the progress bar are from mik itself, not the PHPUnit tests. Their output is summarized at the bottom of the output.

**Comment by mjordan** [comment]
@patdunlavey I've cleaned up the docs for this manipulator based on your earlier [feedback](https://github.com/MarcusBarnes/mik/issues/263#issuecomment-257560771). Please [take a look](https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-InsertXmlFromTemplate) and let me know if they still aren't clear.

**Comment by patdunlavey** [comment]
The doc changes look great. And I wrote a phpunit test for InsertXMLFromTemplateManipulator. Pull request is [here](https://github.com/MarcusBarnes/mik/pull/269).

Thanks!!!!!

**Comment by mjordan** [comment]
@patdunlavey thanks, tests pass for me. I'll merge into issue-263 and then merge that branch into master. @MarcusBarnes any objections?

**Comment by MarcusBarnes** [comment]
@patdunlavey @mjordan No objections.  Thanks for the awesome work.

**Comment by mjordan** [comment]
OK, will merge now. Indeed @patdunlavey thanks. We'd be interested to hear if you have any other use cases or suggestions.

**Comment by mjordan** [comment]
All merged into master. You may need to run `composer dump-autoload` before everything works.

Closing this issue. Thanks both!
