### ISSUE TITLE
CsvCompound: Fails if metadata_filename or child_title not provided

### ISSUE THREAD

**Issue by patdunlavey** [MarcusBarnes/mik#267]
I could not get a CsvCompound toolchain to run unless I provided values for `metadata_filename` and `child_title`. Both values are expected to be present in the __construct() method for CsvCompound. (`src/writers/CsvCompound.php:41-44`).

It could be that an older version of php, or php with different settings, does not fail.

Possible solutions are:

1. Fix documentation to reflect the fact that these values are (or may be) required.
2. If there is a php settings fix, document it.
3. Fix the code so that they are not required.

**Comment by mjordan** [comment]
@patdunlavey I wrote that toolchain, so I'll take a look. Might not be for a day or two however. Will report back here when I've found something.

**Comment by mjordan** [comment]
@patdunlavey they are both required. Not mentioning `metadata_filename` is an omission. Not mentioning that `child_title` is required is a confusing convention; we (mainly I) indicate when a configuration option is optional but not when it is required. If adding 'Required' to entries that are required is clearer (and it is), I'll do that. Sorry for the confusion, and thanks for the feedback.

**Comment by mjordan** [comment]
I've added "Required." to all options' entries in all toolchain wiki pages that were not already indicated as 'Optional."

**Comment by patdunlavey** [comment]
Thanks!
