### ISSUE TITLE
Language of field not being populated

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#27]
Using the format of the mappings file as defined in #7, the Language of field is not being populated. For example, a mappings file with a row like this:

`Publisher,eng,<originInfo><publisher>%value%</publisher></originInfo>,`

should produce markup like this:

```xml
<originInfo>
    <publisher lang="eng">Vancouver School of Art</publisher>
</originInfo>
```
Currently, the markup being produced is like this:

```xml
<originInfo>
    <publisher>Vancouver School of Art</publisher>
</originInfo>
```

**Comment by MarcusBarnes** [comment]
This issue no longer needs to be addressed as the default mappings file format no longer contains the "language of field" column.  Please see these comments: in https://github.com/MarcusBarnes/mik/issues/7#issuecomment-110496088.
