### ISSUE TITLE
Test on PHP 7

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#271]
PHP 7 is becoming more common. Our installation requirements indicate "PHP 5.5.0 (or higher)" so we should be clear about what "higher" means.

**Comment by whikloj** [comment]
I am using this with PHP 7.1.3 so I can open issues if I start to have issues that seem specific to PHP 7.

**Comment by mjordan** [comment]
7.0 and 7.1 are passing travis, and we've had no reported issues from userland. Anyone mind if I close this?

**Comment by MarcusBarnes** [comment]
Travis CI tests for PHP 7.x added in pull-request https://github.com/MarcusBarnes/mik/pull/474 (merged with commit https://github.com/MarcusBarnes/mik/commit/df1682c91409179c6d6e7002a5b3320dae2bc588).
