### ISSUE TITLE
Update oai_dc_to_mods.php postwrite hook script

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#275]
The XSLT provided by @bondjimbond in https://github.com/MarcusBarnes/mik/pull/274 uses a PHP extension (trim_date()). The oai_dc_to_mods.php postwrite hook script I added in #255 doesn't contain that function. I'll also remove the XSLT stylesheet I pushed up in #255 since the one provided in https://github.com/MarcusBarnes/mik/pull/274 is much more complete.

I'm documenting how to use oai_dc_to_mods.php in the cookbook entry at https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Generating-MODS-from-OAI_DC.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/276 (merged into master with commit https://github.com/MarcusBarnes/mik/commit/472b0df298d11f62bbc84e2d99ca21cb0404a267).
