### ISSUE TITLE
Start reviewing code for compliance with PSR2

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#277]
Our README_DEV.md file recommends running PHP_CodeSniffer. I've been reluctant to do this against existing, production-tested code for fear of introducing recursion errors. Now that we are writing more tests ([example 1](https://github.com/MarcusBarnes/mik/issues/238), [example 2](https://github.com/MarcusBarnes/mik/blob/master/tests/MetadataManipulatorTest.php#L148)), we can probably start thinking about running existing code through PHP_CodeSniffer. The CONTENTdm toolchains are challenging to test, so we'll need to be careful with performing code cleanup on those classes.

I propose the following:

* All new code should pass PRS2 checks performed with PHP_CodeSniffer
* We retroactively clean up all test code to conform to PSR2 since we will be able to tell right away if we introduce any errors in it
* We retroactively clean up all CSV toolchain code and manipulators that apply to these toolchains since we will have test coverage for all of that code.

**Comment by mjordan** [comment]
I'm doing some work on #238 and am running PHP_CodeSniffer against the new test files.

**Comment by whikloj** [comment]
I just did [all the files](https://github.com/whikloj/mik/commit/b7f7d0ad09c6e57e7c5bb7b9b8fae7733ef35627) to comply with PSR-2.
The majority was handled by `phpcbf` the rest were line lengths, having arguments with a default at the end of a function signature. I just removed the default as it was `$settings = null` and **mik** doesn't work without a `$settings` so I can't see why the function would give a default `null`. 
There were also 2 function names that had to be changed, the only one I would be concerned about external use of was the `MikTwigExtension::TwigTruncate` which had to be changed to camelCase (`MikTwigExtension::twigTruncate`)

**Comment by mjordan** [comment]
Wow, this a huge amount of work. If you want to open a PR I will test. @MarcusBarnes any objections?

**Comment by MarcusBarnes** [comment]
No objections.

**Comment by mjordan** [comment]
My smoke tests:

1. `git checkout new_master`
1. `composer dump-autolad`
1. `vendor/bin/phpcs --standard=PSR2 /home/mark/Documents/hacking/mik/src`
1. `phpunit  --bootstrap vendor/autoload.php tests` (note, no more `exclude-group`!)
  * All tests pass but one is risky
1. Ran MIK with half a dozen or so configuration files testing various toolchains. *None failed, and none left errors in the MIK logs.*

@whikloj this is `awesome`. What an excellent way to celebrate Canada 150 :heart: Also your reorg of the tests directory is super. Just super.

So, if we merge these changes into master, what other of the huge amount of recent work that you did will break? Cause, unless @MarcusBarnes has any objections, I think this should get into master ASAP.

**Comment by whikloj** [comment]
@mjordan I think most of this would slide in pretty easily. I'd need to remove my FileFetcher as the name would conflict with your FileFetcher, but other that it and its test and assets. I can do that and open a PR if you'd like.

**Comment by whikloj** [comment]
I'll also note I added a nice composer command (credit to @acoburn) so a `composer test` will run both PSR2 and phpunit tests. Also I moved the phpunit.xml file to the main directory so you can just run `phpunit` in the root repo directory and it should work. But for travis I just use the above mentioned `composer test`. 
See [here](https://github.com/whikloj/mik/blob/new_master/composer.json#L32-L35) for the composer script definition and [here](https://github.com/whikloj/mik/blob/new_master/.travis.yml) for the revised travis file.

**Comment by mjordan** [comment]
@whikloj yes please, open a PR.

WRT your fetcher, what does it do that the one we merged last week (docs at https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Using-the-Filesystem-fetcher) doesn't do, other than use a regex to limit the files it recognizes? Maybe we can combine the two fetchers? Would the packages created by yours be ingested by the basic Islandora Batch (e.g., single-file content models)?

**Comment by whikloj** [comment]
I'm not sure of the differences, I think they are that mine will recurse
directories and has the regex file name filter. Otherwise, yours calls the
fetchermanipulator and mine doesn't.

As for the ingest type...I haven't gotten there yet. I got side tracked. :)

**Comment by whikloj** [comment]
@mjordan https://github.com/MarcusBarnes/mik/pull/424

**Comment by MarcusBarnes** [comment]
Initially addressed in  pull request https://github.com/MarcusBarnes/mik/pull/424  (merged with commit https://github.com/MarcusBarnes/mik/commit/a432ff634db51c1fa7c12458bb50bfb20881e60f).  Thank you @whikloj.
