### ISSUE TITLE
In the CSV toolchains, if MODS is only datastream in datastreams[] list, don't require source files

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#284]
In the CSV Single File toolchain (and possibly others), if there is no source file in the `[FILE_GETTER] input_directory`, MIK will not generate MODS files, even if MODS is the only datastream indicated in the `[WRITER] datastreams[]` list. This makes testing metadata creation on developer laptops, for example, impossible unless source files are present. We should allow an empty value for `[FILE_GETTER] input_directory` in CSV toolchains as long as MODS is the only datastream being generated.

**Comment by mjordan** [comment]
Proposed solution is to add logic like this to the code that skips outputting an object is it can't find the source files:

```php
        if ($this->datastreams != array('MODS')) {
            if (!file_exists($source_file_path)) {
                $this->log->addWarning("Source file does not exist, skipping writing package",
                    array('source_file' => $source_file_path));
                return;
            }
        }
```

**Comment by mjordan** [comment]
Logic added for all four Csv toolchains. All PHPUnit tests pass.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/289 (merged in commit https://github.com/MarcusBarnes/mik/commit/37ae197e46c5d761c1c1de4b28377bd92d0003d9).

**Comment by mjordan** [comment]
For the record, wiki pages for CSV single file, compound, books, and newspapers have been updated to document this feature.

**Comment by bondjimbond** [comment]
Need to add some documentation for this feature... Filename field can't be blank, must have unique string in each row (even if it's garbage) or will write over and over to same file.

**Comment by mjordan** [comment]
A resolution to #297 will mean we won't need to mention those things, correct?
