### ISSUE TITLE
SplitRepeatedValues: Repeating wrapper element

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#286]
Either the Wiki documentation needs clarification about how to do this, or it simply doesn't work...

Under metadata_parser:
repeatable_wrapper_element[] = subject

Under manipulators:
`metadatamanipulators[] = "SplitRepeatedValues|disciplines|/subject/topic|;"
`
Mapping file:
`disciplines,<subject><topic>%value%</topic></subject>`

Desired output:
```
  <subject>
    <topic>Social Media</topic>
  </subject>
  <subject>
    <topic>Social Psychology and Interaction</topic>
  </subject>
  <subject>
    <topic>Sociology</topic>
  </subject>
  <subject>
    <topic>Sociology of Culture</topic>
  </subject>
  <subject>
    <geographic>surrey, b.c.</geographic>
  </subject>
  <subject>
    <cartographics>
      <coordinates>49.183333, -122.85000000000002</coordinates>
    </cartographics>
  </subject>
```

Actual output:
```
  <subject>
    <topic>Social Media</topic>
    <topic>Social Psychology and Interaction</topic>
    <topic>Sociology</topic>
    <topic>Sociology of Culture</topic>
    <geographic>surrey, b.c.</geographic>
    <cartographics>
      <coordinates>49.183333, -122.85000000000002</coordinates>
    </cartographics>
  </subject>
```

Is there a specific way to configure it to get the desired output, or is the configuration correct and something wrong with the manipulator?

Note that I'm having similar problems with repeating name elements..

**Comment by mjordan** [comment]
@bondjimbond I'll take a look at this today.

**Comment by bondjimbond** [comment]
Doing a search in the repository, "repeatable_wrapper_element" doesn't seem to appear anywhere in the actual code - just in documentation. Does putting the phrase in the config file map it to a variable with a different name, or was this a feature that didn't get merged?

**Comment by mjordan** [comment]
It's in both metadataparsers/mods/CsvToMods.php and metadataparsers/mods/CdmToMods.php.

**Comment by bondjimbond** [comment]
Ah, never mind then. Github's search function just isn't friendly.

**Comment by mjordan** [comment]
Yeah, it's pretty mediocre.

**Comment by mjordan** [comment]
@bondjimbond It's documented wrong. The *correct* spelling for the option is `repeatable_wrapper_elements[]` (plural). Sorry about that, I've corrected it on the wiki page. Also, this manipulator doesn't work consistently if you're also running the Filter MODS Topic manipulator, but that's OK since this one is intended to be a replacement for Filter MODS Topic.

**Comment by bondjimbond** [comment]
After processing a number of files with the corrected spelling, I'd say it's working (pending of course the resolution of #293). I'm comfortable closing this one.

**Comment by mjordan** [comment]
Thanks @bondjimbond
