### ISSUE TITLE
CSV checks are missing some configuration options

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#287]
['FETCHER']['field_delimiter'], ['FETCHER']['field_enclosure'], and ['FETCHER']['escape_character'] are not used by the validation function (called with the `--checkconfig` option) `checkCsvFile()`.

**Comment by mjordan** [comment]
@MarcusBarnes To test, run the PHPUnit teests.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/288 (closed with commit https://github.com/MarcusBarnes/mik/commit/69b3902b2eea367ca687c005e5f30361207cb571).
