### ISSUE TITLE
CSV Compound toolchain fails on Windows

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#290]
I spent a handful of hours finding this one. :frowning: The CSV Compound toolchain fails on Windows because the DIRECTORY_SEPARATOR constant on Windows is a `\`. https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvCompound.php#L230 uses it within a regex pattern, which had the effect of escaping the next character, causing the match to fail.

I have a fix and will open a PR this evening.

**Comment by mjordan** [comment]
I'll also check the book and newspaper CSV toolchains to make sure they don't also suffer from this bug.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request  https://github.com/MarcusBarnes/mik/pull/305 (merged with commit https://github.com/MarcusBarnes/mik/commit/9cda145293a8009fbd2c410d059dde6980c2eece).
