### ISSUE TITLE
CSV Compound toolchain should skip input directories that contain only one child file

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#291]
Currently, if an input directory for the CSV Compound toolchain contains a single child file, e.g.:

input_directory/
├── compounddobject1
│   ├── image_01.tif
├── compounddobject2
│   ├── image_01.tif
│   ├── image_02.tif
│   ├── image_03.tif
│   └── image_04.tif

a compound object containing one child will be generated. MIK should provide an option to either skip generating this object or to generate it. Use case for generating it is that the object may get additional children in the future.

Perhaps an option in the CSV compound `[WRITER]` section like `min_children` would be useful.

**Comment by mjordan** [comment]
Mini-gist reminder to self: put

```php
        if (count($children) < $this->min_children) {
            $this->log->addWarning("Number of child files is lower than configured minimum",
                array('Record ID' => $record_id));
                return;
        }
```

at the very top of `->writePackages()`.

**Comment by MarcusBarnes** [comment]
@mjordan The relevant pull-requests that address this issue have been merged into master.  We need to update the wiki and related documentation regarding the `min_children` configuration setting and default value.
