### ISSUE TITLE
SplitRepeatedValues metadata manipulator fails if values to split contain a regex character or an ampersand

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#293]
If values in a field that SplitRepeatedValues is being applied to contain any of ` . \ + * ? [ ^ ] $ ( ) { } = ! < > | : -`, the regex used to get the markup fails. `&` is not a reserved regex character but its presence is also causing the regex (or some other part of the code) to fail. Discovered working with @bondjimbond.

**Comment by mjordan** [comment]
Most recent commits do the following:

* Escape regex special characters in raw field values so that regex does not fail if one of the characters is present in the field value to split. This change also means that MIK will complete processing all input more often.
* Adds better logging (to manipulator.log or configured equivalent) when regex that splits the field value does fail. Log entries look like this:
  * for a successful split, one log entry for each constituent value: `[2016-11-24 07:50:31] config.INFO: SplitRepeatedValues {"Record key":"image01","Source field name":"Foo","Source field value":"one; two; three","Output":"<extension><foo type=\"some custom value\">one</foo></extension>"} []`
  * for a failed split: `[2016-11-24 07:50:31] config.WARNING: SplitRepeatedValues {"Record key":"image04","Source field name":"Foo","Source field value":"This; value will crash & burn; badly","Failed regex":"#^(.*)(This; value will crash & burn; badly)(.*)$#"} []`

Recovering from and logging the failed splits is something that should have been there all along, but at this point it's also an admission that I have no idea why regexes on values that contain an ampersand are failing.

@bondjimbond if you could test the issue-293 branch on the input data that contains values with ampersands, I'd appreciate it. You'll have to look in your manipulator log to see the logged failures and fix those MODS files manually.

**Comment by bondjimbond** [comment]
I'll test it today. So this commit doesn't address the ampersand problem, just the regex?

**Comment by bondjimbond** [comment]
Tested it with the CSV that brought up the error in the first place -- all records processed!

**Comment by mjordan** [comment]
Thanks, that's good to hear. Check your manipulator log to see which values weren't split. The  commits address the ampersand problem by failing, logging the failure, and moving on. To allow ampersands someone would have to figure out why they are causing the failure. I gave up after 2 hours.

**Comment by mjordan** [comment]
@MarcusBarnes, since this fix has passed @bondjimbond's smoke test, could you merge the issue-293 branch at your convenience?

**Comment by bondjimbond** [comment]
CORRECTION: All but one records processed. The very last record not processed. Doesn't show up in the PROBLEM RECORDS log either.

However, this is probably unrelated to the issue discussed here.

**Comment by mjordan** [comment]
Is it in mik.log?

**Comment by MarcusBarnes** [comment]
@mjordan When you think it's ready enough, please create a pull-request.

**Comment by mjordan** [comment]
@MarcusBarnes thanks, will do so as soon as @bondjimbond can confirm that the missing record is unrelated to this issue.

**Comment by bondjimbond** [comment]
Sent an email to @mjordan with details about the missing record problem; appears completely unrelated to this issue, so I think it's ready for a pull request.

**Comment by mjordan** [comment]
Agreed, it's almost certainly unrelated. I'll open a PR now.

**Comment by MarcusBarnes** [comment]
Initially addressed in pull-request https://github.com/MarcusBarnes/mik/pull/295 (merged with commit https://github.com/MarcusBarnes/mik/commit/ca6e38f6ca50ffebf25db9c3a202829ba31724d3).  Thank you @mjordan and @bondjimbond for your work on this issue.
