### ISSUE TITLE
Wiki: Create Migration Guides for various repositories

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#298]
As I'm going through the process of migrating KPU from Digital Commons, it seems logical to document the process for other Digital Commons users (and save them several weeks' worth of configuring and debugging). It would be nice to have Migration Guide pages on the wiki, to take people through some known working pathways to successfully migrating with MIK.

I'd be happy to document my process migrating KPU if you're all right with me creating a wiki page or two in your repo.

**Comment by mjordan** [comment]
I'd be happy to do one for CONTENTdm as well.

**Comment by mjordan** [comment]
Some notes for the CONTENTmd guide:

## Overview

MIK provides several toolchains designed for migrations from CONTENTdm to Islandora. Detailed documentation on these toolchains is available:

* [CONTENTdm single file](https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CONTENTdm-single-file-objects)
* [CONTENTdm generic compound](https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CONTENTdm-Generic-Compound)
* [CONTENTdm newspapers](https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CONTENTdm-newspapers)
* [CONTENTdm books](https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CONTENTdm-books)
* [CONTENTdm compound PDF documents](https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CONTENTdm-compound-PDFs)

This migration guide provides general context for migrating from CONTENTdm to Islandora using MIK using these toolchains and documents some processes that are not directly related to the toolchains.

## Differences between CONTENTdm and Islandora

* Descriptive metadata in CONTENTdm is stored in simple key/value pairs. Descriptive metadata in Islandora is stored in XML, with MODS being the default and most common schema.
* Islandora can store user-facing content such as JPEGs and PDFs, and also store "master" files such as TIFFs. CONTENTdm does not store master files such as TIFFs. MIK provides tools for combining offline masters with the web-facing files from CONTENTdm into complete Islandora ingest packages, provided the master files are named consistenly. Islandora can also store preservation and technical metadata such as FITS for each object. 
* Islandora supports hierarchial objects via the Compound Solution Pack, but one difference is that books in Islandora are not heirarchical. Books migrated from CONTENTdm to Islandora lose their hierarchy. Also, currently, there is MIK toolchain or Islandora batch ingest module to migrate hieirarchical non-book compound objects.
* Islandora does support compound PDFs, but not as their own content type; they are just ordinary compound objects whose child objects are PDF files. MK's  "CONTENTdm compound PDF documents" toolchain lets you combine CONTENTdm's compound PDF objects into a single multiplage PDF.
* In CONTENTdm, each object can belong to only one collection. In Islandora, an object can be in any number of collections.

## Understanding your CONTENTdm collections

* https://github.com/mjordan/cdminspect
* Collections in both CONTENTdm and Islandora support multiple content types. Migrations using MIK will typically require mulitple migration runs, one for each content type being migrated.


## Supplementing or correcting your CONTENTdm metadata during migration

## Combining master files with files retrieved from CONTENTdm

## Ingesting batches of objects into Islandora

* Islandora provides both a graphical user interface and a command-line tool for batch loading content.

**Comment by bondjimbond** [comment]
Digital Commons guide in progress: https://github.com/MarcusBarnes/mik/wiki/Migration-Guide:-Digital-Commons

**Comment by bondjimbond** [comment]
Digital Commons guide more or less complete - I have added documentation from Linda Woodcock about how to export metadata spreadsheets from the DC admin interface.

**Comment by mjordan** [comment]
First complete draft of the CONTENTdm migration guide is now available at https://github.com/MarcusBarnes/mik/wiki/Migration-Guide:-CONTENTdm. Comments are welcome!

**Comment by MarcusBarnes** [comment]
Once the first draft of the CONTENTdm migration guide is fully posted (i.e., added to the wiki Table of Contents), we should consider closing this issue and creating separate documentation issues for specific migration guides and or migration cookbook documentation.   Thank you @bondjimbond and @mjordan for your awesome initial drafts.

**Comment by mjordan** [comment]
Sounds like a plan. I've linked the CONTENTdm guide from the wiki table of contents. @bondjimbond if you agree with this plan feel free to close.
