### ISSUE TITLE
Make HTTP requests more robusts against network connectivity and latency issues

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#3]
Currently, MIK is uses several methods that use the [file_get_contents] (http://php.net/manual/en/function.file-get-contents.php) function.  This makes MIK particularly susceptible to network connectivity (say, if the network cuts out momentarily) and latency issues for larger collections.  Below are some suggestions for approaches that may make MIK more robust against these network issues when reading remote files:

* Use [Guzzle](http://docs.guzzlephp.org/en/latest/) - a PHP HTTP client and framework for consuming RESTful web services
* Use [cURL](http://php.net/manual/en/book.curl.php) for its enhanced error reporting, and add appropriate logic and logging to make error handling more robust.
* Investigate how Drupal's  [drupal_http_request](https://api.drupal.org/api/drupal/includes!common.inc/function/drupal_http_request/7) function was implemented for ideas on how to create more robust file request methods within MIK.

Other suggestions are welcome.  Please comment below.

**Comment by mjordan** [comment]
Guzzle has a component called Retry-Subscriber (https://github.com/guzzle/retry-subscriber) that looks like it should be useful. Can be installed via composer.

**Comment by mjordan** [comment]
First implementation in 81b6eead95b141f551ab011255038396212221e2.

**Comment by mjordan** [comment]
We should implement Guzzle in the other filegetters, in order to mitigate against slow response times on the CONTENTdm server due to backup jobs, etc. I can do the CdmNewspapers filegetter if you want.

**Comment by MarcusBarnes** [comment]
That would be great.  Thank you.

**Comment by mjordan** [comment]
@MarcusBarnes can you take a look to make sure that how I've implemented error catching in https://github.com/MarcusBarnes/mik/blob/issue-3/src/filegetters/CdmNewspapers.php#L107 (and similar at lines 220, 252, 277)?

**Comment by mjordan** [comment]
@MarcusBarnes I've added logging to the Guzzle calls. Take a quick look? https://github.com/MarcusBarnes/mik/blob/issue-3/src/filegetters/CdmNewspapers.php#L115

I tested by turning off my network connection half way through a job. Pointers showed up in problem_records.log and Guzzle errors showed up in mik.log.

**Comment by MarcusBarnes** [comment]
:thumbsup: Tested with a CT SpecificSet batch.  It appears to function as expected.  When I disconnected the network, the pointers showed up in problme_records.log and the Guzzle errors were recorded in the mik.log.   Thank you @mjordan for your work on this.

**Comment by mjordan** [comment]
Great, thanks. I'll incorporate this into the CdmSingleFile filegetter as well.

**Comment by MarcusBarnes** [comment]
@mjordan That would be awesome.  Thank you.

**Comment by mjordan** [comment]
Done in 169597c1615de0ab015491937be2ff3843098cca. I think we can merge issue-3 into master and close this issue. @MarcusBarnes any reason not to do that?

**Comment by mjordan** [comment]
... and now CdmPhpDocument is done.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.  I don't see any reason to not to merge.  I'll double check and then go ahead if everything looks good.  Thanks again for the contribution.

**Comment by mjordan** [comment]
Merged into master.
