### ISSUE TITLE
Using the configuration file to pass parameters to metadatamanipulators

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#30]
It may be useful to be able to pass parameters to metadata manipulators via the configuration file.  For example, the breakTopicMetadaOnCharacter method of the FilterModsTopic metadatamanipulator class splits topic metadata on a delimiter which is now a parameter (see https://github.com/MarcusBarnes/mik/issues/26).   One way we might consider doing this in the MANIPULATORS section of the configuration file is by following the named metadata manipulator with a piped delimited list of parameters:

[MANIPULATORS]
; One or more metadatamanipulators classes
metadatamanipulators[] = FilterModsTopic|param1|param2|...

Thought and use cases are appreciated.

**Comment by mjordan** [comment]
I can't think of a better way to define multiple metadata manipulators in the config file, so let's go with this syntax.

One comment though - in CONTENTdm metadata, the semicolon can be used in any field to delimit "repeated" values. In the spirit of avoiding field- or source-specific language, I'd like to suggest that we define the manipulator that splits repeated values on a delimiter not be specific to "topic".

**Comment by MarcusBarnes** [comment]
Regarding your comment: Should we remove field- or source-specific language from FitlerModsTopic, we'd need to make "topic" a parameter, so that the refactored version of FilterModsTopic would be able to determine the correct text-node child element of which MODS element to split on a delimiter.  This will be a good test case for the providing parameters in the configuration file.  Thank you for your comment.
