### ISSUE TITLE
SplitRepeatedValues vs FilterModsTopic

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#307]
The Wiki currenlty says that SplitRepeatedValues is a "more general alternative to FilterModsTopic" (https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-SplitRepeatedValues).

Given that FilterModsTopic's functionality is duplicated here, AND that some bugs are fixed in this more general application, should (a) documentation be updated to say that FilterModsTopic is deprecated, and/or (b) FilterModsTopic be removed entirely?

**Comment by mjordan** [comment]
I'm happy with removing FilterModsTopic. @MarcusBarnes any objections? It is used in the [tutorial](https://github.com/MarcusBarnes/mik/wiki/Tutorial) but I can update that. It's mentioned on https://github.com/MarcusBarnes/mik/wiki/Manipulators but, strangely, searching the wiki for 'filter' doesn't find this page. I don't think it's mentioned anywhere else, but I could be wrong.

**Comment by MarcusBarnes** [comment]
@mjordan I have no objections to removing the FilterModsTopic metadata manipulator given that it has been superseded by SplitRepeatedValues.

**Comment by bondjimbond** [comment]
@mjordan Odd, when I type "filter" into the Wiki filter, the page does come up.

**Comment by mjordan** [comment]
.ini file in tutorial files updated, but I can't modify the wiki page as I'm still getting 500 errors from github.

**Comment by mjordan** [comment]
OK, Github had to clear a cache to resolve the 500 errors on this repo (fallout from yesterday's issues).

I've updated https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-FilterModsTopic to say this manipulator is deprecated, and have cleaned up any other references to it I can find, including the tutorial page. I'll open a PR later today to remove the class file.

**Comment by mjordan** [comment]
@bondjimbond OK to close this issue?

**Comment by bondjimbond** [comment]
Sounds good to me.
