### ISSUE TITLE
Title of compound CSV child objects needs to be HTML escaped

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#311]
CSV Compound child object that don't have their own row in the .csv input file get a generic title based on their parent's title. While parent titles that contain HTML special characters work as expected, titles in child MODS files generated from the parent title need to have the title escaped.

**Comment by mjordan** [comment]
Fix applied to CSV newspaper and book toolchains as well.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.   Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/312 (merged with commit https://github.com/MarcusBarnes/mik/commit/4b2fa9e2c4804279697e90a4600c4ce292554edc).
