### ISSUE TITLE
Clean up the CSV Newspaper writer code

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#316]
The CSV Newspapers writer contains some [cruft](https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvNewspapers.php#L91-L108) and some [misleading](https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvNewspapers.php#L119) or [incomplete ](https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvNewspapers.php#L121)comments. This should be cleaned up.

**Comment by mjordan** [comment]
Related issue is #365.

**Comment by MarcusBarnes** [comment]
@mjordan Has this issue been adequately addressed in the merged pull-request https://github.com/MarcusBarnes/mik/pull/387 to merit closing the issue?  Thanks.

**Comment by mjordan** [comment]
Closed with #387 PR.
