### ISSUE TITLE
Documenet min_children configuration setting.

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#318]
Document the `min_children` configuration setting for compound toolchains.  See issue https://github.com/MarcusBarnes/mik/issues/291.

**Comment by mjordan** [comment]
OK, I've updated the `[WRITER]` section of the CSV Compound toolchain wiki page:

* min_children: Optional. The minimum number of child objects allowed in compound objects. If the number of children in a compound object is less than this number, MIK will skip creating the corresponding ingest package and log that it has been skipped. Defaults to 2.

**Comment by mjordan** [comment]
@MarcusBarnes we can close this issue, I've updated the CSV Compound toolchain wiki page.
