### ISSUE TITLE
CONTENTdm compound PDF documents with only one page cannot be migrated

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#319]
CONTENTdm compound PDF documents with only one page fail to migrate, because the "page" element in their structural metadata is different than that of a compound PDF document that has more than one page. We can see this by dumping the `$document_structure` variable at [line 106](https://github.com/MarcusBarnes/mik/blob/master/src/filegetters/CdmPhpDocuments.php#L106) of the file getter class:

```
$ php -c php.ini mik -c faca.ini -l 2
Commencing MIK.
Filtering 2 records through the CdmCompound fetcher manipulator.
..php
Creating 2 Islandora ingest packages. Please be patient.
int(1)  // <- This is a pointer.
array(2) { // <- This is the output of var_dump($document_structure).
  ["type"]=>
  string(12) "Document-PDF"
  ["page"]=>
  array(3) {
    ["pagetitle"]=>
    string(6) "Page 1"
    ["pagefile"]=>
    string(9) "1.pdfpage"
    ["pageptr"]=>
    string(1) "0"
  }
}
int(13) // <- This is a pointer.
array(2) { // <- This is the output of var_dump($document_structure).
  ["type"]=>
  string(12) "Document-PDF"
  ["page"]=>
  array(2) {
    [0]=>
    array(3) {
      ["pagetitle"]=>
      string(6) "Page 1"
      ["pagefile"]=>
      string(10) "12.pdfpage"
      ["pageptr"]=>
      string(2) "11"
    }
    [1]=>
    array(3) {
      ["pagetitle"]=>
      string(6) "Page 2"
      ["pagefile"]=>
      string(10) "13.pdfpage"
      ["pageptr"]=>
      string(2) "12"
    }
  }
}
```

Result is that the PDF for this object is not retrieved, and errors like this one are written to the mik.log:

```
[2017-02-08 10:54:33] ErrorException.ERROR: ErrorException {"message":"Undefined offset: 0","code":{"pointer":1,"document_structure":{"type":"Document-PDF","page":{"pagetitle":"Page 1","pagefile":"1.pdfpage","pageptr":"0"}},"temp_file_path":"m:\\production_loads\\faca\\temp\\faca_1.tmp"},"severity":8,"file":"M:\\mik_mark\\src\\filegetters\\CdmPhpDocuments.php","line":108} []
```

I propose we add logic to account for this difference. 

I also propose that if we're going to touch the classes used in this toolchain, we may as well resolve #223 in the same PR.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you for spotting this.

**Comment by mjordan** [comment]
OK, have fix and can open PR. Mind if I roll in #223, which I've also fixed and tested?

**Comment by MarcusBarnes** [comment]
Yes, please roll in your fix to #223.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/320 (merged with commit https://github.com/MarcusBarnes/mik/commit/3613a3d5ae49a6828d278a4171ce4b2575fa7e4a).

**Comment by mjordan** [comment]
Thanks!
