### ISSUE TITLE
fetchers/Csv must implement queryTotalRec and getItemInfo

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#32]
Class mik\fetchers\Csv contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (mik\fetchers\Fetcher::queryTotalRec, mik\fetchers\Fetcher::getItemInfo).

Please note that phpunit will fail until this issue is addressed.

**Comment by MarcusBarnes** [comment]
Address in commit 8f0ea30ec95a21f16b21f7765019969a0fe08ea8, however, the implementation specific details were left out.

Please note that phpunit still fails, but for a different reason.

**Comment by mjordan** [comment]
Done in 1fdafb457d6ff58dcac2728c2dda7bcb1c344441.
