### ISSUE TITLE
CSV fetcher should tolerate empty lines in input metadata file

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#321]
Blank lines in the CSV input metadata file will produce an error indicating that the blank rows links didn’t have the same number of columns as the header row.  Since empty rows may be common in the wild, MIK should not produce an error but rather log the presence of the blank line and move on to the next one without an error.

**Comment by mjordan** [comment]
@MarcusBarnes I have introduced blank lines into the tutorial_metadata.csv file on both Linux and Windows and as far as I can tell, they do not cause any problems. My mik.log and problem.log are clean, and all iipqa tests pass on the output.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you for the follow up.  I was able to view the error on an install on Ubantu and a Mac.  These were new installs of MIK, so I wonder if it related to one of the dependencies.  Have you done a `composer update` recently?

**Comment by mjordan** [comment]
I've run `composer update` on both machines and rerun MIK and still can't produce any problems. What was the specific error that the blank lines caused?

**Comment by MarcusBarnes** [comment]
Running `--checkconfig` all should produce:

`Error with CSV input file: it appears that row 7 does not have the same number of colums (1) as the header row (7).`

**Comment by mjordan** [comment]
I get the same output with `--checkconfig all` but when I run MIK to produce packages (i.e., without checkconfig), there are no entries in mik.log or problem.log. All 5 pairs of JPEG and XML files are generated. So it looks like checkconfig picks up the blank lines but the lines have no effect on MIK's output. Can you confirm that your packages and logs look OK?

**Comment by mjordan** [comment]
Separate but related issue, noted here so it's not forgotten: the `-cc` option (short form of `--checkconfig`) no longer works:

```
./mik -c /tmp/tutorial/tutorial_config.ini --checkconfig all
Commencing MIK.
Mapping snippets are OK
Paths are OK
Input directory paths are OK.
Error with CSV input file: it appears that row 5 does not have the same number of colums (1) as the header row (7).
Error with CSV input file: it appears that row 8 does not have the same number of colums (1) as the header row (7).
mark@mark-XPS-13-9343:~/Documents/hacking/mik$ ./mik -c /tmp/tutorial/tutorial_config.ini -cc all
ERROR: Unable to parse option -c: Expected an argument 
```

**Comment by mjordan** [comment]
I've opened #322.

**Comment by MarcusBarnes** [comment]
@mjordan I'm able to generate the packages when I comment out the included metadatamanipulator line: 

`metadatamanipulators[] = "SplitRepeatedValues|Subjects|/subject/topic|;"`

**Comment by mjordan** [comment]
Sounds like the packages are malformed because of the blank rows - is that the case?

**Comment by MarcusBarnes** [comment]
@mjordan Apologies - it looks like I introduced a typo while testing the tutorial config file.  I've updated my comment above.   I'm able to generate the packages.  It's just the misleading message when using the `--checkconfig all` option.

**Comment by mjordan** [comment]
No problem. What say you to closing this issue but continuing the discussion over at #323?
