### ISSUE TITLE
Provide a utility function for logging the value of a variable

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#324]
It would be useful for developers and testers to be able to dump the value of a variable to mik.log or a separate debug  log. Something similar to Drupal's `drupal_debug()` function. Possibly something like:

```<?php
/**
 * Utility function to dump a variable to a log.
 *
 * @param $variable mixed
 *   The variable to dump.
 * @param $label string
 *   A label to dump along with the value. Defaults to ''.
 * @param $dest string
 *   A path to a log file. Defaults to location of mik.log.
 */
function mik_dump($variable, $label, $dest) {
  // Log output of var_export($variable, true);
}
```

**Comment by mjordan** [comment]
@MarcusBarnes where do you think this function should be defined? We don't have a 'utilities' namespace. I'm tending to think that it would be useful to have one, but at the same time I can't think of any other utility classes we'd need. Perhaps there are some other methods we use across multiple toolchains that would fit into a 'utilities' class? On the other hand, we have an 'exceptions' namespace with only one class in it. What do you think?

**Comment by MarcusBarnes** [comment]
Address in pull-request https://github.com/MarcusBarnes/mik/pull/375 (merged with commit https://github.com/MarcusBarnes/mik/commit/b331cfa54693b3ee620a355d36520700811b4de2).

**Comment by MarcusBarnes** [comment]
@mjordan I like the idea and it provides for use-cases we haven't considered yet, especially once MIK is used as part of digitization workflows and not just for helping migrate content.

**Comment by mjordan** [comment]
Cookbook entry is at https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Inspecting-a-variable's-value.
