### ISSUE TITLE
.gitattributes not working, master branch is borked

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#329]
Doing a fresh clone to a Linux machine shows that some files are being marked as modified:

```
/tmp$ git clone https://github.com/MarcusBarnes/mik.git
Cloning into 'mik'...
remote: Counting objects: 4204, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 4204 (delta 2), reused 0 (delta 0), pack-reused 4192
Receiving objects: 100% (4204/4204), 976.82 KiB | 596.00 KiB/s, done.
Resolving deltas: 100% (2746/2746), done.
Checking connectivity... done.
mark@mark-XPS-13-9343:/tmp$ cd mik/
mark@mark-XPS-13-9343:/tmp/mik$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   extras/scripts/postwritehooks/object_timer.php
	modified:   extras/sfu/mappings_files/icohc_mappings.csv
	modified:   src/metadatamanipulators/InsertXmlFromTemplate.php
	modified:   src/metadatamanipulators/NormalizeDate.php
	modified:   src/metadatamanipulators/SplitRepeatedValues.php
	modified:   src/metadatamanipulators/SplitRepeatedValuesInJson.php

no changes added to commit (use "git add" and/or "git
```

`git diff` shows that all lines in each file are being marked as changed, which suggests that it's the line endings that git is detecting as different. I suspect that each of these files was last updated on Windows (some of them quite a while ago, well before #310. Why are they showing up now? And how do we fix this?

Github provides advice at https://help.github.com/articles/dealing-with-line-endings/. I've followed the steps in the "Refreshing a repository after changing line endings" section and `git status` now shows the same list of files above as having been modified. `git diff` shows no output:

```
/tmp/mik$ git status
warning: CRLF will be replaced by LF in extras/scripts/postwritehooks/object_timer.php.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in extras/sfu/mappings_files/icohc_mappings.csv.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in src/metadatamanipulators/InsertXmlFromTemplate.php.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in src/metadatamanipulators/NormalizeDate.php.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in src/metadatamanipulators/SplitRepeatedValues.php.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in src/metadatamanipulators/SplitRepeatedValuesInJson.php.
The file will have its original line endings in your working directory.
On branch master
Your branch is up-to-date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	modified:   extras/scripts/postwritehooks/object_timer.php
	modified:   extras/sfu/mappings_files/icohc_mappings.csv
	modified:   src/metadatamanipulators/InsertXmlFromTemplate.php
	modified:   src/metadatamanipulators/NormalizeDate.php
	modified:   src/metadatamanipulators/SplitRepeatedValues.php
	modified:   src/metadatamanipulators/SplitRepeatedValuesInJson.php

mark@mark-XPS-13-9343:/tmp/mik$ vi .gitattributes 
mark@mark-XPS-13-9343:/tmp/mik$ 
mark@mark-XPS-13-9343:/tmp/mik$ git diff
mark@mark-XPS-13-9343:/tmp/mik$ 
```

@MarcusBarnes do you think it's a good idea for me to push up to master the changes in these files that these steps have resulted in? That should correct the line endings on these files. Currently, master is broken for me since one of the files listed above is always showing as being modified. I can't even reset or check out the file (neither of these actions does anything). Therefore I can't switch between branches.

I still am puzzled that this is showing up now though.

**Comment by MarcusBarnes** [comment]
@mjordan Just tested on my Mac and I don't experience the same issue.  I assume you're cloning into a brand new directory.  I'm going to ask a someone who is using Ubantu to see if they can reproduce.

**Comment by mjordan** [comment]
Yes, that's correct, it's a completely new clone into its own directory. Thanks for testing.

**Comment by MarcusBarnes** [comment]
I'm going to test using my development Islandora Vagrant machine and report back.

**Comment by mjordan** [comment]
I just cloned to a second Linux machine, and `cd`ing into the mik directory and running `git status` shows the same modified files.

**Comment by MarcusBarnes** [comment]
@mjordan I can confirm this behavior via my Islandora Vagrant instance.  Thank you for spotting it.

**Comment by mjordan** [comment]
@MarcusBarnes thanks for the sanity check. Should I open a PR after correcting the problem as described above?

**Comment by MarcusBarnes** [comment]
@mjordan Yes - a pull-request is best.  I'll review on my Mac (where I don't get the issue) and on a Linux machine.    Thank you in advance.

**Comment by mjordan** [comment]
Tested and looks good.
