### ISSUE TITLE
Add implementation details to fetchers\Csv queryTotalRec and getItemInfo

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#33]
Please add implementation specific details to the queryTotalRec and getItemInfo methods in fetchers\Csv class.

Please see the related issue https://github.com/MarcusBarnes/mik/issues/32.

**Comment by mjordan** [comment]
@MarcusBarnes I'll take a stab at this over the weekend.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.  Much appreciated.

**Comment by mjordan** [comment]
Done in 1fdafb457d6ff58dcac2728c2dda7bcb1c344441.
