### ISSUE TITLE
Add migration guide for SFU's Editorial Cartoons collection

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#335]
Following the example of @bondjimbond's https://github.com/MarcusBarnes/mik/wiki/Migration-Guide:-Digital-Commons, I would like to add a guide documenting the migration of our Editorial Cartoons Collection. The source platform is a total one-off that uses a MySQL backend and a custom public front end. I will spin this guide as more of a "migrating from a custom platform" task using the CSV single file toolchain. @MarcusBarnes I might also be able to get some good content for our upcoming MIK workshop out of this task.

**Comment by mjordan** [comment]
Draft is at https://github.com/MarcusBarnes/mik/wiki/Migration-Guide:-Simon-Fraser-University-Library-Editorial-Cartoons-Collection. Comments are welcome.

**Comment by mjordan** [comment]
Feedback from Ian on this draft was that we may want to include mention of the issue I raise in [this Google Groups thread](https://groups.google.com/forum/#!topic/islandora/cm_6zCt-3PY). In a nutshell, if we map the 'cartoon text' to MODS title, we'll have some objects (about 400 out of 11,600) whose Fedora object 'label' property is longer the the maximum allowed 255 characters. I'm waiting to hear back from Jannette about where we should be storing the cartoon text in the MODS. I'd like to hold off on publishing this guide until we resolve this question and can include mention of it.

**Comment by bondjimbond** [comment]
My suggestion re where to store the caption is in the MODS abstract element. For the title/label I'd probably go with a combination of newspaper and date, if not also the author.

**Comment by mjordan** [comment]
I've done a "day after" editing job on this guide, e.g. cleaned up some awkward paragraphs, broken out some dense passages into better writing for the web, and added some additional examples. I also added a description of our iterative workflow while testing our mappings file.

I'm going to wait until we come to a landing on the long-title question and add a bit about that, then actually migrate the collection (ha), then link this to the wiki home page.

**Comment by mjordan** [comment]
I've updated the migration guide to include our solution to the long title problem, and have linked it from the wiki table of contents.

**Comment by mjordan** [comment]
Going to close this issue and open another related one.

**Comment by mjordan** [comment]
Related issue is #361.
