### ISSUE TITLE
OAI toolchain: Add Set ID config option

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#336]
Add an option to include a Set in the OAI request. 

e.g. http://oclscore.ca/vital/oai/provider?verb=ListRecords&metadataPrefix=oai_dc&set=SCSet

To allow the extraction of objects from a particular set/collection/etc.

**Comment by mjordan** [comment]
It is there already, see https://github.com/MarcusBarnes/mik/wiki/Toolchain:-OAI-PMH-for-repositories-that-identify-resource-files-in-a-record-element under the `[FETCHER]` section.

**Comment by bondjimbond** [comment]
Ack, I totally missed this. Thanks.

**Comment by bondjimbond** [comment]
However - could it perhaps be tweaked to run multiple queries in sequence, and add the results of each set to a separate subdirectory within the output_directory? 

This may be a separate issue and a more complex feature.

**Comment by mjordan** [comment]
Sure, open an separate issue for using multiple setspecs.
