### ISSUE TITLE
OAI toolchain: document To/From config options

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#337]
OAI toolchain includes the feature to limit results by date. The method for doing this needs to be documented in the wiki.

**Comment by mjordan** [comment]
Totally. My bad. I will fix.

**Comment by mjordan** [comment]
Done - @bondjimbond please take a look in the `[FETCHER]` section of the wiki page and let me know if my docs are OK.

**Comment by bondjimbond** [comment]
Makes sense. Maybe add the to and from parameters in the example too, to make it completely clear.

**Comment by mjordan** [comment]
OK, examples in yyyy-mm-dd format added.

**Comment by bondjimbond** [comment]
Looks good!
