### ISSUE TITLE
PHPUnit tests failing

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#34]
Running phpunit --bootstrap vendor/autoload.php tests creates fatal errors.

Please update the code and related so that phpunit runs successfully.  Additionally, identify potential unit tests to add in separate issues.

**Comment by mjordan** [comment]
Happy to help - got any more details?

**Comment by MarcusBarnes** [comment]
On my system, I get the following error from PHPUnit:
"Fatal error: Cannot instantiate abstract class mik\fetchers\Fetcher in /Applications/MAMP/htdocs/mik/tests/FetcherTest.php on line 11."

**Comment by mjordan** [comment]
I removed tests/FetcherTest.php, which removed the error, and updated tests/CsvTest.php so that it now passes.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.  I've just tested the issue-34 branch.  I'll merge momentarily and open a more general issue for adding tests for the 1.0 milestone.  Please feel free to add comments and suggestions to that issue once it's open.  Thanks again.

**Comment by MarcusBarnes** [comment]
Closed with commit 757c376ddd6663934db954c967310faa88b8bddc.

**Comment by MarcusBarnes** [comment]
The more general issue for adding Unit Tests and other quality control features for the 1.0 milestone release:  https://github.com/MarcusBarnes/mik/issues/132
