### ISSUE TITLE
Add link to KORA

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#342]
Now that the KORA institutional repository is live in Arca, we should add it to the list in the main MIK README of collections migrated using MIK:

arcabc.ca/islandora/object/kora:root

We could even include a link to @bondjimbond's [migration guide](https://github.com/MarcusBarnes/mik/wiki/Migration-Guide:-Digital-Commons).

**Comment by bondjimbond** [comment]
Better to use the official KORA URL: http://kora.kpu.ca
Unless you like to point specifically to root Islandora collection, in which case it would be http://kora.kpu.ca/islandora/object/kora:root

**Comment by mjordan** [comment]
Nothing wrong with http://kora.kpu.ca. I'll open a PR.
