### ISSUE TITLE
OAI toolchain - MIK confuses quotes with directory name on some(?) computer(s)

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#345]
I ran into some truly bizarre behaviour today. Installed MIK on another computer so that I could leave it running the OAI-PMH download over the weekend. I used the exact same config file I use on my own computer, but on the other Mac it generated errors.

It expected a trailing slash in my output_directory setting.

Original (failed):
`output_directory = "/tmp/oaitest_output"`

Edited (success):
`output_directory = "/tmp/oaitest_output/"`

However, `temp_directory = "/tmp/oaitest_temp"` worked as normal, no adjustment needed.

MIK ran successfully with the adjustment, but I could not find the files in the expected directory. mik.log and problem_records.log appeared in `/tmp/oaitest_output` as expected, and all the temporary files appeared in the temp_directory.

After some searching, I discovered that the files were being saved to the following path:

`/Users/(username)/mik/“/tmp/oaitest_output/“/`

For some reason, the output_directory parameter processed quotation marks as directory names. But only on this computer.

For reference: the second computer is running the same OS and a slightly newer version of PHP than my first computer (5.5.38 vs 5.5.36)

Any idea what's going on?
@mjordan @MarcusBarnes

**Comment by mjordan** [comment]
What happens if you don't use quotation marks around your paths? I think they are only necessary if there is a space or an escape character in the .ini value.

**Comment by bondjimbond** [comment]
Don't know; I'll have to check on Monday.

**Comment by mjordan** [comment]
@bondjimbond should we leave this issue open or can we close it?

**Comment by bondjimbond** [comment]
Let's leave open for now... I haven't had a chance to try anything. Regardless, it's an issue; either a documentation one ("Don't use quotes here") or a code fix.

**Comment by mjordan** [comment]
http://php.net/manual/en/function.parse-ini-file.php indicates that

> If a value in the ini file contains any non-alphanumeric characters it needs to be enclosed in double-quotes (").

So it would appear that we must wrap paths that contain non-alphanumeric characters (`/`, `.`, `_`, `-`, etc.) in double quotes. I'll confirm this behavior and update https://github.com/MarcusBarnes/mik/wiki/Configuring-MIK and the toolchain pages accordingly.

**Comment by mjordan** [comment]
@bondjimbond is this still an issue?

**Comment by bondjimbond** [comment]
@mjordan Hard to say. I don't have access to the Mac where the problem showed up, and my own Mac works fine. So perhaps this should be closed, and reopened if anyone else ever runs into the same problem?

**Comment by mjordan** [comment]
Yes, let's close and reopen when necessary.
