### ISSUE TITLE
Add a filegetter for the OAI toolchain that fetches OBJ datastreams from Islandora

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#347]
We have to filegetters that work with OAI-PMH toolchains, one for Open Journal Systems and one for OAI-PMH providers that include a full URL to a payload file. The first is really just a demo while the latter has already been used in production.

The OJS filegetter scrapes values from HTML, so it is brittle. It would be useful to provide a filegetter that doesn't require a full URL in the OAI metadata, since few systems provide such a URL. Islandora, for example, is only guaranteed to provide a PID in its OAI DC metadata.

An OAI-PMH toolchain that would be known to work with Islandora itself (for single-file objects anyway) would also be useful for workshops and other hands-on training, as an alternative to using CSV toolchains.

**Comment by bondjimbond** [comment]
Is this much different from my OAI filegetter for Vital (which isn't really Vital-exclusive)? This lets you set:

- Base URL for download link
- Datastream IDs to download

And cycles through the DSIDs in order until it finds a valid one. This is useful to Islandora too, given that not all objects have OBJ datastreams (i.e. some have PDF instead).

Maybe better, more generalized to tweak the Vital version to allow config to append a suffix (i.e. "/download") so that it works for Islandora too?

[OaipmhVital_2.php.txt](https://github.com/MarcusBarnes/mik/files/856587/OaipmhVital_2.php.txt)

**Comment by mjordan** [comment]
I think this would work, but you get you record key from the OAI identifier:

```php
$pid = preg_replace("/oai:SGOCLSAPP1:/","",$record_key);
```

My filegetter parses the DC metadata to get the record key. I think that if I changed mine to get the key from the OAI identifier, and we provided a base URL option that allowed us to insert the record key into the URL, e.g., `base_url = http://foo.org/object{id}/whatever`, the two filegetters could use your code.

**Comment by mjordan** [comment]
Getting the record key from the OAI identifier may be problematic. Islandora uses identifiers like `oai%3Adigital.lib.sfu.ca%3Asome_pid` whereas Vital produces identifiers like `oai:SGOCLSAPP1:some_pid`. In order to use the same filegetter, we can provide a configuration option that will allow variable patterns in the identifiers. An .ini file setting defining the pattern like `pid_in_oai_identifer = oai%3Adigital.lib.sfu.ca%3A{PID}` would work, as long as the extracted value of {PID} was ready to use in requests. If both PIDs can be reconsituted by replacing the '_' with a ':', we could get this to work; not sure about how other platforms we might want this filegetter to work with handle the ':' in PID embedded in the OAI identifier.

Given that the purpose of the filegetter in the PR is primarily to provide something to use during the upcoming workshop, I'm not sure it's worth combining the two. We don't necessarily want a proliferation of filegetters, but for for a filegetter to work it needs to deal with the specifics of the platform it is harvesting from. I think your Vital filegetter and the one in the PR do that well for their respective platforms. I'm not sure it's worth adding extra configuration to be able to combine the two, especially given that each one is less than 90 lines long. I'm leaning towards keeping them separate and therefore specific to their intended purposes.

**Comment by bondjimbond** [comment]
For Vital you could get it from the <identifier> element as well, actually; I don't quite remember why it was done this way. But I agree that the easy thing to do is to leave both as-is; may be worth combining them in the future when one/both of us has more time.

**Comment by mjordan** [comment]
OK, given the narrow scope of the Islandora filegetter let's keep them separate for now. I'll add some additional text to the file-level comment to make its purpose clearer.

**Comment by MarcusBarnes** [comment]
Initially address in pull-request https://github.com/MarcusBarnes/mik/pull/348 (merged with commit https://github.com/MarcusBarnes/mik/commit/a8b85d936558bc3b3e6712f47f946aab8233f597).

**Comment by bondjimbond** [comment]
Reiterating the note I made above: what about objects in CModels without an OBJ datastream? (i.e. theses, citations, etc.) Can the filegetter be tweaked to accommodate several different DSIDs? Either by configuration, or hard-coding them in (as there are only a handful of different DSIDs that Islandora uses for the original object file).
