### ISSUE TITLE
CSV Newspapers: Mishandling columns in CSV?

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#349]
I'm running into strange behaviour with the CSV Newspapers toolchain. MIK seems to be unable to recognize the presence of data in one of the columns, starting from a certain point.

In the attached CSV, MIK correctly processes the first 3 rows. But from the 4th row onward, MIK logs the following error:

> [2017-03-21 18:42:15] metadataparsers.WARNING: Mappings file contains a row that is not in source CSV row for this object. {"Record key":"ASMN-00004","Missing field in metadata":"Issue Title"} []

Data in the Issue Title column is identical from rows 1-3 and from 4-onward, except for dates. I'm unable to figure out why this is happening.

Also: the MODS.xml files generated for the individual pages DO contain the title information:
`  <titleInfo>
    <title>Abbotsford Post, page 2</title>
  </titleInfo>
  <originInfo>
    <dateIssued encoding="w3cdtf">1923-01-13</dateIssued>
  </originInfo>`

I can't identify any problems in my CSVs, and since the page files that MIK generates DO contain the "missing" element, is it possible that the toolchain has a bug?

Also note: I tried deleting the first three rows of data, to see if moving row 4 to the top would change anything. All rows claim to have the title field missing.

[ASMN-CSV-1920s_original.csv.txt](https://github.com/MarcusBarnes/mik/files/859307/ASMN-CSV-1920s_original.csv.txt)

[ASMN-MODSMapping.csv.txt](https://github.com/MarcusBarnes/mik/files/859309/ASMN-MODSMapping.csv.txt)

@mjordan @MarcusBarnes for your experience with this toolchain in particular..

**Comment by mjordan** [comment]
Two questions:

1. Is the place where the strange behavior starts reproducible? In other words, does the error start at the same row all the time?

1. My gut tells me that there may be some unprintable characters in your CSV that are causing this. The CSV parser that we use is very robust but we've seen instances in the past where BOMs (byte order marks) and other nonprintable characters throw it for a loop.

I'll take a look at your data files later today to see if I can narrow things down. I hope I can reproduce the problem without needing access to the TIFF files.

**Comment by MarcusBarnes** [comment]
What happens when you run using the `--checkconfig all` option?

**Comment by mjordan** [comment]
@bondjimbond FYI this toolchain came after our migration, which used the CONTENTdm Newspapers toolchain. Like with other non-CONTENTdm toolchains, you're the first one to use them in production.

**Comment by bondjimbond** [comment]
`--checkconfig all` looks good:
> d142-058-130-245:mik Brandon$ ./mik --config ufv_newspapers_sample.ini --checkconfig all
> 
> Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /Users/Brandon/mik/vendor/monolog/monolog/src/Monolog/Logger.php on line 311
> Commencing MIK.
> Mapping snippets are OK
> The path /tmp/Volumes/UNTITLED/output/ufv_newspapers_temp (defined in configuration setting temp_directory) does not exist but will be created for you.
> The path /tmp/Volumes/UNTITLED/output/ufv_newspapers_temp (defined in configuration setting temp_directory) does not exist but will be created for you.
> The path /Volumes/Untitled/output/ufv_newspapers_output (defined in configuration setting output_directory) does not exist but will be created for you.
> Paths are OK
> Input directory paths are OK.
> CSV input file appears to be OK.

**Comment by MarcusBarnes** [comment]
@bondjimbond Thank you for confirming.  Another quick thing to double check is to to run `composer update` and or `composer dumb-autoload`.  I'm assuming that you're using the latest commit from master.

**Comment by bondjimbond** [comment]
Sigh... Well, over lunch I unplugged the hard disk I was writing to and had some problems afterward, so I reformatted it and renamed it -- and after renaming the target disk, the title field is working.

So - I have no explanation for why it changed, but it's working now. I doubt I could replicate the problem.

**Comment by bondjimbond** [comment]
Closing the issue since it solved itself in a weird way and I'd probably have a hard time duplicating it.

**Comment by MarcusBarnes** [comment]
Interesting that the error manifested the way it did.  For reference, the error message is generated in this block https://github.com/MarcusBarnes/mik/blob/master/src/metadataparsers/mods/CsvToMods.php#L103-L109.
