### ISSUE TITLE
CdmPhpDocuments.php is consuming excessive memory

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#35]
`file_put_contents()` at https://github.com/MarcusBarnes/mik/blob/master/src/writers/CdmPhpDocuments.php#L56 is throwing an "Allowed memory size of xxx bytes exhausted" error even if the PHP CLI `memory_limit` setting is 512M.

The source PDF file's contents are retrieved at https://github.com/MarcusBarnes/mik/blob/master/src/filegetters/CdmPhpDocuments.php#L67. Perhaps a way to avoid keeping the entire source PDF file's contents as a string in memory would be to write the file to disk in this function, then in the writer class simply move it to the destination create by `file_put_contents()`. This would increase disk activity but that's probably easier to deal with than memory allocation.

If this solution is acceptable, I can take a stab at this.

**Comment by mjordan** [comment]
Just occurred to me that we probably won't be able to use PHP's `fwrite()` since it also writes a string. Maybe this a good opportunity to incorporate Guzzle, since it can [write to a stream](http://stackoverflow.com/questions/16939794/copy-remote-file-using-guzzle).

**Comment by MarcusBarnes** [comment]
@mjordan If you would like to take a stab at this issue, please do so.  As you mention, this may be a good opportunity to give Guzzle a test within the code base.  Thank you for your input and assistance.

**Comment by mjordan** [comment]
Implemented in branch issue-35 and ready for testing/merging. Note: this fix introduces a new configuration option in the FILE_GETTER .ini file section, `temp_directory`, which is where the content retrieved by the Guzzle request is written before being moved to the output directory (if not set defaults to '/tmp'). You'll also need to run `composer dump-autoload` and `composer update` to get this to work.

**Comment by mjordan** [comment]
Also note that Guzzle requires PHP 5.5.0 or higher.

**Comment by mjordan** [comment]
Can this branch be merged into master?

**Comment by MarcusBarnes** [comment]
Please go ahead and merge.

**Comment by mjordan** [comment]
Done with 6019abe945ac19dea01a0c013ec1087df34f1ab7.
