### ISSUE TITLE
Add a shutdown hook script to clear out the temp_directory

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#354]
It is useful to delete the contents of the MIK temp directory between runs, especially if you are playing with metadata generation options. We should provide a shutdown script (thanks again @jpeak5!) to do this. It would be registered like this:

```
[WRITER]
shutdownhooks[] = "php extras/scripts/shutdownhooks/delete_temp_directory.php"
```
I have this script ready, and will open a PR to include it. @bondjimbond should test since he suggested it.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/355 (merged into master with commit b5d76dcfc49a943f37e6662d0e5abdf1621cc143).

**Comment by mjordan** [comment]
Thanks! I'll add mention of the script to https://github.com/MarcusBarnes/mik/wiki/Shutdown-hooks

**Comment by jpeak5** [comment]
Mark,

Thanks for drawing attention to our xslt in the mik wiki.

LSU Librarians @myqua and @carakey have evolved the xsl quite a bit on our fork of mik, and I wonder if we might open a new pull request to submit those changes as well as some documentation describing their use in a little more depth.

jrp

Sent from my iPhone

On Mar 24, 2017, at 2:28 PM, Mark Jordan <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! I'll add mention of the script to https://github.com/MarcusBarnes/mik/wiki/Shutdown-hooks

**Comment by mjordan** [comment]
@jpeak5 totally. PR is welcome.
