### ISSUE TITLE
--checkconfig on mappings files ignores commented out mappings

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#356]
If a mappings file contains a commented-out row (using the #), `--checkconfig` ignores the commenting and reports errors, etc. in the mapping. `--checkconfig` should probably respect the #.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/357 (merged with commit https://github.com/MarcusBarnes/mik/commit/86d21316384b1d66afe418c6d4322ec7765202fb).
