### ISSUE TITLE
Document the OAI-PMH Islandora OBJ filegetter class.

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#358]
https://github.com/MarcusBarnes/mik/blob/master/src/filegetters/OaipmhIslandoraObj.php

**Comment by mjordan** [comment]
Thanks, will do.

**Comment by mjordan** [comment]
Here's a draft. I hope it is clear that this toolchain is for demonstration purposes only.

https://github.com/MarcusBarnes/mik/wiki/OAI-PMH-for-Islandora-repositories

**Comment by mjordan** [comment]
Gentle bump on this one too, the docs don't need to be perfect.

**Comment by mjordan** [comment]
Closing this, it's been linked from the list of toolchains for some time.
