### ISSUE TITLE
Islandora OBJ Filegetter: get other DSIDs

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#359]
Reiterating the note I made in #347: This filegetter is hard-coded to grab OBJ files. What about objects in CModels without an OBJ datastream? (i.e. theses, citations, etc.) Can the filegetter be tweaked to accommodate several different DSIDs? Either by configuration, or hard-coding them in (as there are only a few different DSIDs that Islandora uses for the original object file).

@mjordan

**Comment by mjordan** [comment]
Yes, I think we should add the ability to check for other DSIDs, using your Vital configuration options as a model. I'll probably get to it this weekend.

**Comment by mjordan** [comment]
PR is merged, closing.
