### ISSUE TITLE
Metadata manipulators are only being applied to mappings from Subject

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#36]
The `if` statement at https://github.com/MarcusBarnes/mik/blob/issue-35/src/metadataparsers/mods/CdmToMods.php#L131 is only applying metadata manipulators to mappings that from "Subject" fields in the source metadata.

**Comment by MarcusBarnes** [comment]
Initial work was carried out to address this issue at commit 16e44fc6ad322e0c202311b51311eb48621a7037 and some additional improvements at 0dfbff636563d7a36cdeb8a6c19541414b67903a.
