### ISSUE TITLE
Add a Twig extension to truncate titles on word boundaries

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#361]
MIK's [InsertXmlFromTemplate]( https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-InsertXmlFromTemplate) metadata manipulator uses the Twig templating engine to generate MODS xml. Since titles [longer than 255 characters are problematic in Islandora](https://groups.google.com/forum/#!searchin/islandora/255%7Csort:relevance/islandora/cm_6zCt-3PY/JuMnRDQfEQAJ), one solution to populating MODS `<title>` elements with truncated text is to use a Twig template like this:

```xml
{% if Title|length < 256 %}
  <titleInfo>
     <title>{{ Title }}</title>
  </titleInfo>
{% else %}
  <titleInfo>
     {# Note that "slice" is not wordsafe. #}
     <title>{{ Title|slice(0, 250) }} [...]</title>
  </titleInfo>
{% endif %}
```
Problem is, Twig's [slice](http://twig.sensiolabs.org/doc/2.x/filters/slice.html) filter does not respect word boundaries.

I'd like to propose that we include a custom Twig filter as part of the InsertXmlFromTemplate metadata manipulator that will truncate strings on word boundaries. Adding a custom filter is documented at http://twig.sensiolabs.org/doc/2.x/advanced.html, and requires that the code for the filter be registered as part of the Twig environment, which in this manipulator is defined at https://github.com/MarcusBarnes/mik/blob/master/src/metadatamanipulators/InsertXmlFromTemplate.php#L54. We could probably use the "class method" implementation by defining the method within the InsertXmlFromTemplate class file itself, since that is where we need to register the custom filter.

SFU's solution to the 255-char-max title issue may not be useful to other sites, but the custom Twig filter is not specific to that use case, it can be used to truncate any string at a word boundary.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/362 (merged with commit https://github.com/MarcusBarnes/mik/commit/aa03acab4a6f1e8382312ad6838443a591f95958).
