### ISSUE TITLE
Add a metadata parser that generates XML files from Twig templates

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#363]
MIK's uses the Twig templating engine to generate top-level MODS element markup via the [InsertXmlFromTemplate]( https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-InsertXmlFromTemplate) metadata manipulator. It would be useful to use Twig to generate complete metadata XML files. Such a metadata parser would not use mappings but would insert values from fields directly into the template.

The templates would look like this:

```xml
<?xml version="1.0"?>
<mods xmlns="http://www.loc.gov/mods/v3" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink">
  <titleInfo>
     <title>{{ Title }}</title>
  </titleInfo>
  <name type="personal">
    <namePart>{{ Creator }}</namePart>
    <role>
      <roleTerm type="text">photographer</roleTerm>
    </role>
  </name>
  <abstract>{{ Description }}</abstract>
  <identifier type="local" displayLabel="Local identifier">{{ Identifier }}</identifier>
  <typeOfResource>still image</typeOfResource>
</mods>
```

This metadata parser would be a drop-in replacement for the existing parsers. It would be configured in .ini files like this:

```
[METADATA_PARSER]
class = templated\Templated
template = templated_mods_twig.xml
```

It could generate MODS or DC, or any other output format.

**Comment by mjordan** [comment]
I added a metadata manipulator that does a preg_replace() on the XML file generated by the template.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/364 (merged with commit https://github.com/MarcusBarnes/mik/commit/5139b27e45df0b6f02dae803654b71ec80e2ff15)
