### ISSUE TITLE
SimpleReplace metadata manipulator replaces text matched by pattern with ''

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#367]
The SimpleReplace metadata manipulator replaces the target text found by the regex pattern with a two quotation marks (`''`)  when used as documented:

`metadatamanipulators[] = "SimpleReplace|/foo/|''"`

We should change this behavior so that the second parameter is not required but is optional. If it is not present, the target text found by the regex pattern is replaced with an empty string, that is, it is removed.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/368 (merged with commit https://github.com/MarcusBarnes/mik/commit/53eec7319906f406c19a0b8699d2946b12cd21a6).
