### ISSUE TITLE
Make page filename segment separator in CsvBooks and CsvNewspaper toolchains configurable

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#370]
The character that is used to separate the parts of page-level filenames in the [CSV Newspapers](https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvNewspapers.php#L132) and [CSV Books](https://github.com/MarcusBarnes/mik/blob/master/src/writers/CsvBooks.php#L110) toolchains is hard-coded to be a hyphen (`-`):

```
csvbookstestinput/
├── book0001
│   ├── page-01.tif
│   ├── page-02.tif
│   ├── page-03.tif
│   ├── page-04.tif
│   ├── page-05.tif
│   ├── page-06.tif
│   ├── page-07.tif
│   └── page-08.tif
```

This should be a configurable option for each of those writers, to allow people to avoid having to bulk rename their page image files if they have used some other character. We could add a config option like `[WRITER] page_filename_segment_separator` with a default of `-`.

**Comment by mjordan** [comment]
@MarcusBarnes I can work on this but I'd like to ask if you are OK with my adding a PHPUnit test to test for it and skip the human smoke testing? I don't really see a need to do both.

**Comment by MarcusBarnes** [comment]
@mjordan Adding the PHPUnit test would be great.  Thank you!

**Comment by mjordan** [comment]
One thing I'm finding with opening PRs is that assembling sufficient data for someone to test my work takes a lot of effort. Where that only means creating an .ini file it's not so bad, but in most cases asset files will also be required.  Maybe we could consider making it explicit in the PR that there is a PHPUnit test included (e.g., in the "How should this be tested" section). If the test passes in travis, we don't need a separate smoke test to merge. For PRs where there is no PHPUnit test, we'd still need the smoketest. Thought?

**Comment by mjordan** [comment]
Getting hung up on PHPUnit tests again, but will persist a bit longer.

**Comment by mjordan** [comment]
@MarcusBarnes PHPUnit tests now pass for this new option. To revive my question above from March 31, if we add PHPUnit tests for a new feature/option, and those tests pass, do you think it's necessary to perform an additional smoke test that requires the person opening the PR to assemble test data and configurations? I'm suggesting that if the tests pass, our PR wouldflow could be something like:

1. Person working on issue must incorporate the change into one of the existing PHPUnit tests, or provide new test.
1. Person working on issue must state in the PR template that the tests pass on his local dev copy.
1. Person reviewing PR clones branch, and reruns the tests.
1. If they pass on the reviewer's local dev copy, and the test code looks like it covers the new work, the reviewer can decide if they want to merge into master. Reviewer also has the option of deciding that the tests are not sufficient or that a smoke test involving sample data and configuration is justified.
1. If the person working on the issue does not provide a PHPUnit test, a smoke test is required prior to merging.

What do you think?

**Comment by MarcusBarnes** [comment]
@mjordan I'm in favor of doing as much testing as possible.  However, I realize that creating sample data for each new configuration variation can be too time consuming, especially for certain types of toolchains.   In addition to your points above, I suggest that we start creating tagged releases of the code base (and documentation), running sample data through before each release as a double check between releases.  That way groups of users have some expectation of what to expect with each release.

**Comment by mjordan** [comment]
Sounds like a plan. I'll open a PR for this issue. Maybe we should open a new issue about the new workflow and releases (or even separate ones)? I totally agree we should be doing releases (in fact our main README mentions releases).

**Comment by mjordan** [comment]
OK, PR forthcoming, plus new issues on modified workflow and releases.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/386 (merged with commit https://github.com/MarcusBarnes/mik/commit/ee7c168f8f193a2bfac566fc2a0074d74dcbc145).

**Comment by mjordan** [comment]
Thanks, I'll update the two toolchains' wiki pages.

**Comment by mjordan** [comment]
Done
