### ISSUE TITLE
Checkgconfig all fails for templated metadataparser class 

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#371]
With the inclusion of the new metadata parser class that generates output from Twig templates (templated), the checkconfig functionality needs to be updated to accommodate tool-chain combinations that do not require mappings files.  Please see the comment on the pull-request https://github.com/MarcusBarnes/mik/pull/364#issuecomment-291171505 and the original enhancement issue https://github.com/MarcusBarnes/mik/issues/363.

**Comment by mjordan** [comment]
@MarcusBarnes perhaps the easiest way to deal with this is to change the logic at https://github.com/MarcusBarnes/mik/blob/master/src/config/Config.php#L122 to look for only the metadata manipulators that use mappings files, i.e., CdmToMods and CsvToMods. That way, we can fix this issue for the OAI toolchains as well.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/374 (merged with commit https://github.com/MarcusBarnes/mik/commit/2c910302669ab18609621e2a5602d18676359be6).
