### ISSUE TITLE
Document the Templated metadata parser

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#373]
We need to document the  [new Templated metadata parser](https://github.com/MarcusBarnes/mik/issues/363). Probably best to wait on some discussion at #372.

**Comment by mjordan** [comment]
First draft is at at https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Templated-Metadata-Parser, with the entry for the SimpleReplaceTemplated metadata manipulator at https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-SimpleReplaceTemplated.

**Comment by mjordan** [comment]
@MarcusBarnes or @bondjimbond would you mind taking a look at the draft documentation for this so we can close this issue (and/or improve the docs)?

**Comment by mjordan** [comment]
@MarcusBarnes a little bump on this, if you have time.

**Comment by MarcusBarnes** [comment]
I've reviewed both https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Templated-Metadata-Parser  and https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-SimpleReplaceTemplated.  They both look good.  I'm going to close this issue.  @bondjimbond and others, if you're able to take a look, please do and we can incorporate any feedback you provide.

**Comment by mjordan** [comment]
Thanks @MarcusBarnes. I've linked the cookbook recipe from the Cookbook table of contents and updated all applicable toolchain documentation.
