### ISSUE TITLE
Update toolchain documentation to indicate preserve_content_filenames is optional.

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#376]
As noted in the Additional Notes section of https://github.com/MarcusBarnes/mik/pull/366, we need to update relevant toolchain documentation to indicate that the `[WRITER] preserve_content_filenames` setting is now optional in CSVSingleFIle and CSVJson toolchains (and set to false by default).

**Comment by mjordan** [comment]
I'll take care of this today.

**Comment by mjordan** [comment]
Updated on https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CSV-single-file-objects, but there is no documentation for the CSV to JSON toolchain other than its mention on https://github.com/MarcusBarnes/mik/wiki/Information-for-developers. Related issue is #372.

Maybe we can close this now and I can write a Cookbook entry as per #372?

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.  That works well for me.
