### ISSUE TITLE
Update SimpleReplace Metadata Manipulator documenation (parameters).

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#377]
Documentation at https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-SimpleReplace needs to be updated to reflect changes introduced via pull-request https://github.com/MarcusBarnes/mik/pull/368 (the second parameter is not required but is optional).

**Comment by mjordan** [comment]
Done, please take a look.
