### ISSUE TITLE
Move TwigTruncate code from manipulator class to utility class

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#379]
The custom Twig filter [TwigTruncate](https://github.com/MarcusBarnes/mik/blob/master/src/metadatamanipulators/InsertXmlFromTemplate.php#L124) should be moved to a utility class so it can be shared across all Twig template implementations (other manipulators, metadataparsers, etc). The first instance where we could reuse it is in the [Templated](https://github.com/MarcusBarnes/mik/blob/master/src/metadataparsers/templated/Templated.php) metadata parser.

We could do this by creating a utility class src/utilities/Twig, which would contain all custom Twig extensions.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/380 (merged with commit https://github.com/MarcusBarnes/mik/commit/2eef264e07aec75fd76dcf8658e7b59f24d2b673).
