### ISSUE TITLE
Improve project description and topics

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#382]
Improve the Github project description and use the topics tag feature.

**Comment by MarcusBarnes** [comment]
I've made some improvements to the Github project description and topics.  Please feel free to suggest a better description and or better topic tags to add.  Closing this issue for now.  Thank you.

**Comment by mjordan** [comment]
Looks good @MarcusBarnes , thanks!

**Comment by MarcusBarnes** [comment]
I was actually looking into using something like https://github.com/Richdark/RAKE-PHP  to extract keywords from our Wiki documentation for weighted suggestions on appropriate keywords, but decided that given my other work commitments, that I should leave that for another time. :)
