### ISSUE TITLE
Remove createModsXML() from Mods.php

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#39]
Child classes implement this method so it should be declared as an abstract method.

**Comment by MarcusBarnes** [comment]
The child classes [CsvToMods.php] (https://github.com/MarcusBarnes/mik/blob/master/src/metadataparsers/mods/CsvToMods.php) and [CdmToMods.php](https://github.com/MarcusBarnes/mik/blob/master/src/metadataparsers/mods/CdmToMods.php) use slightly different function signatures for the createModsXML method.  I suggest we adopt the function signature used in CsvToMods.php for createModsXML($collectionMappingArray, $objectInfo) for the abstract method as it will be possible to modify the CdmToMods.php to use this signature.

**Comment by MarcusBarnes** [comment]
FYI:  I have addressed this issue in a local feature branch.  I want to clean up the code a little more before I push my changes.

**Comment by MarcusBarnes** [comment]
Addressed in commit 9a29fce5c9ab262bd110e20151c7faeb8f3ebfed.
