### ISSUE TITLE
Create a shutdown hook that generates compound structure files

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#391]
The Compound Batch module provides a [script](https://github.com/MarcusBarnes/islandora_compound_batch/blob/master/extras/scripts/create_structure_files.php) that generates the compound-object-level structure.xml files required by that module. I know we have discussed whether MIK should generate these files and decided that it shouldn't. However, generating this sort of data is exactly what we introduced MIK shutdown scripts to do.

**Comment by mjordan** [comment]
Related issue is #392.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/399 (merged with https://github.com/MarcusBarnes/mik/commit/b3027ed1036910fdd503af9cf9e209a8311a11e5).

**Comment by mjordan** [comment]
Excellent, thanks, I've updated https://github.com/MarcusBarnes/mik/wiki/Shutdown-hooks to describe this new script.
