### ISSUE TITLE
Write a sample MIK input data generator script

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#393]
It would be really useful to be able to generate some simple content for development and testing. E.g., for each CSV toolchain, write out X number of raw input objects comprised of files created using `touch` based on the tutorial or iCon workshop metadata CSV. The script should also write out a basic .ini file.

**Comment by MarcusBarnes** [comment]
Initial work on this is in pull-request https://github.com/MarcusBarnes/mik/pull/395 (merged with commit https://github.com/MarcusBarnes/mik/commit/f487d3827ca5cfce19f35f801cb4aa52b4c65b5b).  Further work still needs to be done  - best if we close this ticket and create separate issues as appropriate for the compound, book, and newspaper sample file functionality.  @mjordan What do you think?

**Comment by mjordan** [comment]
I'm cool with that approach.
