### ISSUE TITLE
Add support for compound, book, and newspaper issue sample data to the MIK input data generator script

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#397]
As discussed in #393, we need to complete work on th MIK input data generator so that is creates compound, book, and newspaper issue output.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/398 (merged with commit https://github.com/MarcusBarnes/mik/commit/045f58f2b2e4c33d876a7c8297329ede191e7211).

**Comment by mjordan** [comment]
Thanks @MarcusBarnes, I've updated https://github.com/MarcusBarnes/mik/wiki/Information-for-developers.
