### ISSUE TITLE
Provide sample CONTENTdm to MODS mapping file

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#4]
Provide a sample file to populate the mapping_csv_path value in config files. Running mik without a mappings file results in this error:

```
PHP Warning:  fopen(): Filename cannot be empty in /home/mark/Documents/hacking/mik/src/metadataparsers/mods/CdmToMods.php on line 75
Unable to open file.mark@mark-ThinkPad-X230:~/Documents/hacking/mik$ vi /home/mark/Documents/hacking/mik/src/metadataparsers/mods/CdmToMods.php
```

**Comment by MarcusBarnes** [comment]
A basic sample CONTENTdm to MODS mapping CSV file was added in commit c301ea7898f54fb90ff0de82a943a2c90471049e

Please set mapping_csv_path to the be the path to this file in your configuration file under the METADATA_PARSER section.
