### ISSUE TITLE
Config:  input_directories is optional for Cdm toolchains

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#410]
The configuration checking functionality currently assumes that input_directories in the FILE_GETTER section is required not optional.   The [wiki documentation for CdmSingleFile](https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CONTENTdm-single-file-objects#the-file_getter-section) correctly points out that it is optional.  When not included, you'll get a PHP offset error like:

``“PHP Notice:  Uninitialized string offset: 0 in /Users/barnes26/dev/mik/src/config/Config.php on line 273.” ``

Adjusting the logic around line 273 to confirm that `input_directories` configuration seeting exists before proceeding with the other checks should resolve the PHP notice.

**Comment by mjordan** [comment]
@MarcusBarnes I see you assigned yourself, but would you like me to take a crack at this, with you testing?

**Comment by MarcusBarnes** [comment]
That's fine if you have a chance to get to this now.   Thanks.

**Comment by mjordan** [comment]
OK, will do.

**Comment by MarcusBarnes** [comment]
Addressed in pull-request https://github.com/MarcusBarnes/mik/pull/413 (merged with commit https://github.com/MarcusBarnes/mik/commit/a09226465febe91290250050447c55329b3f67a7).
