### ISSUE TITLE
Move to support PHPUnit 6 tests

### ISSUE THREAD

**Issue by whikloj** [MarcusBarnes/mik#419]
This is related to discussion on #415 starting [here](https://github.com/MarcusBarnes/mik/issues/415#issuecomment-311445918)

I have a branch setup with tests working. Git registered 3 tests as deleted and added because the class names were incorrect and so I corrected them at the same time. If you prefer, you can fix those test class names and then it won't (or shouldn't) mess with history of those files.

Branch : https://github.com/whikloj/mik/tree/phpunit-6-tests
Comparison : https://github.com/MarcusBarnes/mik/compare/master...whikloj:phpunit-6-tests?expand=1

I moved the test reference in #418 to be skipped instead of commenting out the code.
Results are 
```
Tests: 53, Assertions: 83, Skipped: 1.
```

**Comment by whikloj** [comment]
I'll also note that I enabled Travis and Codecov on my new_master branch which uses the updated tests and they still pass PHP 5.5, 5.6 and 7

https://travis-ci.org/whikloj/mik

However I'll also note that the testing coverage is quite low (< 30%)
https://codecov.io/gh/whikloj/mik/branch/new_master

**Comment by MarcusBarnes** [comment]
Initially addressed in pull-request https://github.com/MarcusBarnes/mik/pull/424 (merged with commit https://github.com/MarcusBarnes/mik/commit/a432ff634db51c1fa7c12458bb50bfb20881e60f).  Thank you @whikloj!
