### ISSUE TITLE
Allow inclusion of OCR files in book page directories

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#421]
Added similar feature for newspaper issues in #383. Makes me think MIK should be generating all paged content with a single class (maybe a kind of writer?) but I need to get this working ASAP for books here. We can refactor later?

**Comment by mjordan** [comment]
Work on #428 should be merged into master before work on this issue is.

**Comment by mjordan** [comment]
@bondjimbond OK, a fresh new branch that fixes all the nasty PHPUnit tests. Please smoke test at your convenience.

**Comment by mjordan** [comment]
Closed with e7d7ece8ce363fcbe45b94b554dbdafa39ecd421.

**Comment by mjordan** [comment]
@bondjimbond would you mind looking at the "Including page-level OCR files" section of https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CSV-books to see if the part about validation is clear?

**Comment by bondjimbond** [comment]
Seems clear enough!

**Comment by mjordan** [comment]
Thanks, I've updated the corresponding text on https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CSV-newspapers as well.
