### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#422]
I'd like to:

1. Remove the warning at the top of the README about the change in MIK's command syntax as of October 2016.
1. Update the "Current status" section to mention the new fetchers, and
1. Add @whikloj to the list of contributors.

**Comment by mjordan** [comment]
Also in section "Islandora content that has been prepared using MIK" add link to [Abbotsford Sumas and Matsqui News](http://ufv.arcabc.ca/islandora/object/ufv%3A255). Maybe reorganize this list by repository, e.g. "SFU Library", "Arca"?

**Comment by mjordan** [comment]
Maybe defer until we tag 0.9.0?

**Comment by MarcusBarnes** [comment]
Address in pull-request https://github.com/MarcusBarnes/mik/pull/433 (merged with commit https://github.com/MarcusBarnes/mik/commit/0eda1bc9c72b26065e89bee780287123346b584b).  Thank you @mjordan.
