### ISSUE TITLE
Regex in filegetters/CsvBooks.php fails on Windows

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#428]
The regex at https://github.com/MarcusBarnes/mik/blob/master/src/filegetters/CsvBooks.php#L158 fails on Windows, where `DIRECTORY_SEPARATOR` is `\`, which escapes the succeeding character.

Also, the function `determineObjItems()` can be eliminated without loss of functionality.

Once PR #424 has been merged, I'll open a PR to add this cleaned up class.

**Comment by mjordan** [comment]
As far as I can tell, work on this issue should be merged into master before work on #421.

**Comment by MarcusBarnes** [comment]
Address in pull-request  https://github.com/MarcusBarnes/mik/pull/429 (merged with commit https://github.com/MarcusBarnes/mik/commit/830b54df8ca06bcaa985edd07c1968afb38b64bd).
