### ISSUE TITLE
Add method to Fetcher abstract class to check well formedness of snippets in mapping file

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#43]
Since snippets in metadata mapping files are XML, manually creating them is error prone. MIK should check each snippet for well formedness before it proceeds with creating import packages, and if it detects an error, quit and tell the user to check the bad snippet(s). Perhaps a good place for this is in the Fetcher abstract class. I can start this feature.

**Comment by mjordan** [comment]
Maybe putting this check, and the others for URLs, etc., in src/config/Config.php is a better place, since the tests are against configuration information. Any objections to putting them there?

**Comment by MarcusBarnes** [comment]
I have no objections to this.

**Comment by mjordan** [comment]
Options to check mappings snippets, URLs, and file paths are in place. If an .ini option ends in '_url', that value is checked; if it ends in '_path' or '_directory', the value is checked. I decided to make checking a separate, preliminary step to running mik to perform the conversion and have documented the workflow in the README. 

I can merge the feature branch (issue-43) into master whenever is convenient.
