### ISSUE TITLE
Make MIK Codebase Citable with initial tagged release

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#430]
Using the steps in the [citable code guide](https://guides.github.com/activities/citable-code/), it's possible to mint a [DOI](https://en.wikipedia.org/wiki/Digital_object_identifier) to make the MIK code-base more easily citable.

**Comment by MarcusBarnes** [comment]
I created an account with Zenodo.org and enabled release syncing with their system.  When we create a release, it should mint a DOI that we can add to the README to help when people wish to cite the MIK codebase.

**Comment by mjordan** [comment]
Sounds cool.

**Comment by MarcusBarnes** [comment]
I used the [Islandoracon 2017 MIK workshop repository](https://github.com/MarcusBarnes/MIK_workshop_Islandoracon_2017) as a test.  It worked as expected.

**Comment by mjordan** [comment]
Sweet - what's the DOI?

**Comment by MarcusBarnes** [comment]
At the top of the workshop README.md I've added the badge that displays the DOI: 10.5281/zenodo.826891.

**Comment by mjordan** [comment]
Frickin' awesome!

**Comment by mjordan** [comment]
@MarcusBarnes can we close this?

**Comment by MarcusBarnes** [comment]
@mjordan Yes.  I'm closing this now.  Thanks!
