### ISSUE TITLE
CdmNewspaper writer produces errors when packages already exist in output directory

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#46]
The CdmNewspaper writer may produce errors when packages (newspaper issues) already exist in the output directory.  Adding some checks to see if item-level directory and files already exist should resolve this issue.

**Comment by mjordan** [comment]
Thanks for finding this @MarcusBarnes. I'll add an option to all Writer configs to overwrite or not.

**Comment by MarcusBarnes** [comment]
The resolution to this issue https://github.com/MarcusBarnes/mik/issues/175 provides a fix to this as MIK will first check for the existence of the newspaper issue directory and if it exits, create another by  appending a period plus a number at the end of the directory name (for example, 1979-01-23.1).

**Comment by MarcusBarnes** [comment]
Based on my earlier [comment](https://github.com/MarcusBarnes/mik/issues/46#issuecomment-196463809) - I will close this issue for now.
