### ISSUE TITLE
Fix broken images in README, wiki, etc.

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#468]
In the main README and elsewhere, we (meaning mostly I) have linked to images served from Dropbox. These have not worked in some time, since Dropbox changed its public linking policy. We should move these images off Dropboxy and host them on Github directly. On approach I have heard of is to open a issue and attach the images. They will then be sharable across source files, READMEs, wikis, etc. Or, we could add an images directory to the mik repo and put them there. Some of these images are reused from other pages, however. Thoughts?

**Comment by MarcusBarnes** [comment]
Since wiki's are also repos, it may be possible to clone the wiki locally, add a directory like "images/" with the images, push the changes, then use the links to the images in the wiki repo image folder.

**Comment by MarcusBarnes** [comment]
I can create a test repo. with a wiki to confirm that this works or not.

**Comment by MarcusBarnes** [comment]
Sounds excellent!  Thank you for taking on this task.

**Comment by mjordan** [comment]
Works great. I've moved all of the images and the .zip data for the Tutorial into an 'assets/mik_tutorial' directory in the wiki, updated the links in the text of the tutorial page, and it looks good: https://github.com/MarcusBarnes/mik/wiki/Tutorial

Will move on to others soon and will open a PR for fixes to the main MIK README.md file.

**Comment by MarcusBarnes** [comment]
Thank you again @mjordan for fixing the images in the wiki and the README.
