### ISSUE TITLE
Limit package generation - what is expected behaviour?

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#475]
Bringing this up in a new issue, since #445 is closed and this is a separate topic.

If I set --limit 5 in my test run, and objects at lines 1 and 4 are "problem records", MIK will skip over them and generate packages for 2, 3, 5, 6, and 7.

My expectation, since I use the limit option for testing, is that MIK should produce packages for only 2, 3, and 5, showing that objects 1 and 4 failed... that is, my interpretation of the --limit 5 parameter is "Try the first five objects and return the results". MIK's interpretation is "Run MIK, and return 5 successful packages."

Both interpretations are valid, but what would you think is the average user's expectation?

**Comment by mjordan** [comment]
I think we can define expectations by better documentation.  The `--limit` option is intended for testing. I see the results you describe as valid test results: they identify some problem objects and also produce X good packages. Plus I think documenting the current behavior will take a lot less time and effort than changing code.
