### ISSUE TITLE
CdmSingleFile: Blank "input_directories" creates ambiguous error

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#483]
[According to the wiki](https://github.com/MarcusBarnes/mik/wiki/Toolchain:-CONTENTdm-single-file-objects), if you want the OBJ datastream for a given file, you should "Comment out, remove, or use an empty value for input_directories".

If you use an empty value, it fails to download the objects. Instead you get ambiguous errors:

> [2018-08-28 14:25:56] ErrorException.ERROR: ErrorException {"message":"Invalid argument supplied for foreach()","code":{"pointer":657},"severity":2,"file":"/Users/brandon/sfuvault/mik/src/filegetters/CdmSingleFile.php","line":147} []
> [2018-08-28 14:25:56] ErrorException.ERROR: ErrorException {"message":"problem writing package","record_key":657,"details":"[object] (mik\\exceptions\\MikErrorException(code: 0):  at /Users/brandon/sfuvault/mik/mik:105)"} []

Commenting out the line entirely works.

Leaving it empty DOESS work for the CdmCompound toolchain, but not CdmSingleFile.

Simple solution would be to change the instructions in the wiki, but a better solution (keeping functionality consistent between toolchains) would be to make sure that a blank value has the expected result.

**Comment by mjordan** [comment]
I vote for changing the wiki. I'm reluctant to change any code since I don't have a CONTENTdm instance to test against...

**Comment by bondjimbond** [comment]
Changing the wiki sounds good to me. I'll take care of it.
