### ISSUE TITLE
regex_replace filter not available?

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#486]
`[2018-08-29 18:17:47] ErrorException.ERROR: ErrorException {"message":"problem with metadataparser","record_key":669,"details":"[object] (Twig_Error_Syntax(code: 0): Unknown \"regex_replace\" filter. at /Users/brandon/sfuvault/mik/manipulations/athabasca_manipulations_nicknames/coordinates_herbarium.xml:4)"} []`

My code:

```
{% if latitu %}
<subject>
  <cartographics>
    <coordinates>{{ latitu|regex_replace(['/,/','/$/'],['/º/','/N/']) }}, {{ longit }}</coordinates>
  </cartographics>
</subject>
{% endif %}
```
Is there no regex_replace filter available, or did I just do a bad job writing it?

**Comment by mjordan** [comment]
It's not listed at https://twig.symfony.com/doc/1.x/ or at https://twig.symfony.com/doc/2.x/ - where is it documented?

**Comment by bondjimbond** [comment]
https://learn.getgrav.org/themes/twig-filters-functions

https://www.branchcms.com/learn/docs/developer/twig/filters/item/regex-replace

And other places

**Comment by mjordan** [comment]
I think those two platforms provide regex_replace as a Twig extension. It doesn't appear to come as part of Twig itself.

MIK does provide an example of adding a custom extension, twigTruncate, at https://github.com/MarcusBarnes/mik/blob/master/src/utilities/MikTwigExtension.php.

**Comment by mjordan** [comment]
... and I failed to add, we could implement our own regex_replace there if we wanted to.

**Comment by bondjimbond** [comment]
No worries. Looks like I was able to get what I need out of a couple of other functions plus the "replace" function.

**Comment by mjordan** [comment]
Cool. That said, if we want to extend Twig, we can do that.
