### ISSUE TITLE
CLImate progress bar doesn't work on Windows

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#49]
There is a [known issue with the CLImate library on Windows](https://github.com/thephpleague/climate/issues/9). As a quick and dirty workaround, I recommend simply printing dots when MIK is run under Windows to indicate that it is doing something.

**Comment by mjordan** [comment]
Fixed with 1c76ffc410660d33b02ea930e93e19ffa8699c3f. mik and fetchermanipulators (the only places where the progress bar is used) now print periods when run on Windows. The hacky code should be removed once the CLImate issue is resolved.

**Comment by mjordan** [comment]
Just a followup, the fix suggested at the CLImate issue linked above doesn't work for us. I'll document this in the MIK Cookbook and we can remove it when the upstream issue is resolved.

![climate_on_windows](https://cloud.githubusercontent.com/assets/403918/12329000/056fd490-ba93-11e5-9d61-add1a41a54de.png)

**Comment by MarcusBarnes** [comment]
@mjordan Thank you for the update.

**Comment by mjordan** [comment]
Closing.
