### ISSUE TITLE
Create exception class

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#50]
We need to be able to catch errors at any point in the class hierarchy and have them bubble up to the main loop in mik so that if an exception is caught, mik can move on to the next record in the loop after logging the error).

Ideally, we'd have a custom MIK Exception class that was extended by a fetcher exception class, a metadata parser exception class, a writer exception class, etc. I'm not sure how that would work however.

@MarcusBarnes would you mind starting this?

**Comment by MarcusBarnes** [comment]
Initial work on this feature request is provided in commit 99873c86c8f117c388b6670cd13f22a0bb6e4744.  Additional refinements or improvements may be required.  Please open additional specific issues if this is the case.

**Comment by mjordan** [comment]
Nice work @MarcusBarnes - this caught an error in my metadata manipulator code and skipped creation of the affected objects.
