### ISSUE TITLE
Mysterious mapping error?

### ISSUE THREAD

**Issue by bondjimbond** [MarcusBarnes/mik#507]
When running with `--checkconfig all`, I'm suddenly getting an odd error with the mapping file:

`Error: Mapping snippet +ACI-+ADw-titleInfo+AD4APA-title+AD4AJQ-value+ACUAPA-/title+AD4APA-/titleInfo+AD4-+ACI- appears to be not well formed`

This mapping file has worked fine the previous times I've run MIK, and no changes to the Title section were made. Any idea what's happening here?

[Archive.zip](https://github.com/MarcusBarnes/mik/files/4194722/Archive.zip)

**Comment by bondjimbond** [comment]
In fact, all my mappings - hitherto just fine - are now "not well formed".

**Comment by mjordan** [comment]
@bondjimbond sorry, I don't have time to test, but can you clarify that if you use MIK to generate content (i.e, not run its checks), do things work as expected? Perhaps the problem is with the check code. But, as to why it would suddenly stop working like it used to, I have no idea.

**Comment by bondjimbond** [comment]
Nope, it crashes out.

```
Fatal error: Uncaught mik\exceptions\MikErrorException in /Users/brandon/sfuvault/mik/mik:105
Stack trace:
#0 /Users/brandon/sfuvault/mik/src/fetchers/Csv.php(94): {closure}(8, 'Undefined index...', '/Users/brandon/...', 94, Array)
#1 /Users/brandon/sfuvault/mik/src/fetchers/Csv.php(130): mik\fetchers\Csv->getRecords()
#2 /Users/brandon/sfuvault/mik/mik(131): mik\fetchers\Csv->getNumRecs()
#3 {main}
  thrown in /Users/brandon/sfuvault/mik/mik on line 105
```

**Comment by mjordan** [comment]
Have their been any code changes since it stopped working?

**Comment by bondjimbond** [comment]
None. The only difference is that I am running the same .ini file with a new metadata CSV -- but no changes to the mapping file, which is the file that's throwing errors.

**Comment by mjordan** [comment]
I'm sorry, I can't think of why that is happening. Not sure if @MarcusBarnes has any insights.

**Comment by bondjimbond** [comment]
Ack, looks like an OpenOffice problem. Somehow it's saving my files without quoting the cells, even though they're opening with quotes. What the heck.

**Comment by bondjimbond** [comment]
What happened:

- Allowed my Mac to install Numbers
- Numbers made itself the default program for CSVs
- ???
- Numbers messed up my recently-opened CSVs even though they were only opened and saved with OpenOffice

Solution:
- Make sure CSV default is OpenOffice
- Copy an older mapping CSV
- Rewrite
- Seems to work now

**Comment by mjordan** [comment]
Good to hear it was a Numbers problem. Can't go wrong with LibreOffice, in my experience.
