### ISSUE TITLE
Monolog logger creates warning message when date.timezone PHP ini setting not set.

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#54]
A warning message is created by Monolog when date.timezone PHP  ini setting is not set.  We can check for this at the top of the main MIK and set a default date.timezone (I have some code in a local feature branch) - is this a good approach?   Additionally and or alternatively, where's the best place to document this?  Is there a way to check for this setting using composer?

**Comment by mjordan** [comment]
Some googling didn't turn up any hints on how to use Composer to check, but maybe we could add a check using the --checkconfig= option.

**Comment by mjordan** [comment]
@MarcusBarnes I'll close this since you've added

```php
if (null == ini_get('date.timezone')) {
    date_default_timezone_set('America/Vancouver');
};
```

to the top of mik to work around this problem
