### ISSUE TITLE
Add an option to the CSV file writer to write the output to the input directory

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#55]
As per @mark-cooper suggestion. Purpose is to eliminate unnecessary copying of files.

**Comment by MarcusBarnes** [comment]
To clarify, we'd use the same single source files inside the input directory, but write out the metadata and other related files - correct?

**Comment by mjordan** [comment]
Yes, that's what Mark and I discussed. We may also want to rename the files to they conform to the IDs in the CSV file.

**Comment by mark-cooper** [comment]
Thanks for adding this @mjordan 

I wanted to see if I could get something working quickly and this seems to be doing the job:

https://github.com/mark-cooper/mik/commit/93ecb06d377d9bbc40923ff1104dc0a0c5fa0981

I haven't looked at the coding standards or anything like that yet ... should I test some more and pull request?

**Comment by MarcusBarnes** [comment]
Thank you @mark-cooper for the feedback on MIK and for the first go at incorporating this requested enhancement. I'll schedule some time to review and test your code in mark-cooper@93ecb06 and we can take things from there.  Thanks again!

**Comment by MarcusBarnes** [comment]
@mark-cooper  - I've run your contributed code several times to test your modifications.  So far everything functions as expected - thank you for your contribution.  Please issue a pull request and I'll integrate this into master.  It would be good to have some use-case scenarios on the project wiki that describes a use-case where using the settings you've contributed would be a good choice and which describes how to set up MIK for that use-case scenario.

Thanks again @mark-cooper.

**Comment by MarcusBarnes** [comment]
@mark-cooper's pull request https://github.com/MarcusBarnes/mik/pull/56 addresses this feature request and was merged into master with commit https://github.com/MarcusBarnes/mik/commit/bfd74c5e481cdba3c2e98dc0806210f3c3b6a819.
