### ISSUE TITLE
Settings are not accessible to metadata manipulators

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#59]
The $settings property in the FilterModsTopic class is NULL:

```php
/**
     * @var array $settings - configuration settings from confugration class.
     */
    public $settings;

```

Consequently, MIK settings are not accessible through that variable. Settings are accessible to the fetcher and file manipulators. It would be useful to make them accessible to all manipulators, for grabbing the paths to log files, etc. defined in the .ini files.

Perhaps pass settings into manipulators via applyMetadatamanipulators(), like applyFetchermanipulators() does?  Separate but related question (maybe should get its own issue), filegetters don't have an "apply manipulators" function - should they?

**Comment by MarcusBarnes** [comment]
A first go at addressing this issue is in commit 27ac1b9af7defe5210d69b453026cd8064005d90.  The commit should be comprehensive, but if some files related to this issue were not properly updated, please reopen the issue.

**Comment by mjordan** [comment]
@MarcusBarnes thanks, your fix works if I pass  $settings as the first parameter to a child class's constructor and add

```php
parent::__construct($settings);
``` 
to the child constructor. Does that sound right?

**Comment by MarcusBarnes** [comment]
Yes - that is correct.  I note that in the child classes I declared a settings property and used:
```php
$this->settings = $settings
``` 
... inside the constructor.  But as you rightly point out above, I should have simply used 

```php
parent::__construct($settings);
``` 
... inside the child classes constructor.

**Comment by mjordan** [comment]
@MarcusBarnes can we add the change you made in 27ac1b9af7defe5210d69b453026cd8064005d90 to CsvToMods.php?

**Comment by MarcusBarnes** [comment]
This should now be available in CsvToMods.php as of commit d4706b69a7444e842c830258031efa5b00fe4841.
