### ISSUE TITLE
Ability to set metadata and file manipulators in configuration file

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#6]
Engineer a way to have metadata and file manipulators processes metadata and files appropriately by simply setting them in the configuration file.

**Comment by mjordan** [comment]
+1 on this. I could come up with some use cases if that would help.

**Comment by MarcusBarnes** [comment]
Thank you.  Use cases would help.  Additional suggestions for needed or desired filemanipulators and metadatamanipulators would be best added as additional issues with the ToDo label.

**Comment by mjordan** [comment]
Manipulators should be reusable across source-to-target combinations. Some use cases:

filemanipulators: 1) create a TN datastream from an image, PDF or video OBJ datastream, 2) create a PDF from an image OBJ or other datastream, 3) create a TIFF from a JPEG2000 OBJ datastream, 4) validate an XML datastream.

metadatamanipulators: 1) take any date value and convert it to yyyy-mm-dd, 2) take any personal name value and try to invert it to last name, first name format, 3) take any value and look it up against a Linked Data source, for example, a name and look it up in VIAF and return the corresponding URI if there is only one.

If we create reusable, generalized manipulators, we'll need to figure out how to pass configuration values in. For example, for the filemanipulator that creates a TN from  PDF datastream, what program + parameters would you run? For the metadatamanipulator that looks up a value in an external Linked Data source, what query URL do you hit?

**Comment by MarcusBarnes** [comment]
There is some partial work on this issue for metadatamanipulators in 7029a107dbd1667e921910f427a481cef296ea26 and 4f659d770d25391e74e7d4fe6cb22761b9b11aca.

Note the addition of the manipulate() wrapper method of the FilterModsTopic metadatamanipulator class.

**Comment by mjordan** [comment]
I think we can close this Nice work @MarcusBarnes.

**Comment by MarcusBarnes** [comment]
Thank you @mjordan.
