### ISSUE TITLE
CLImate progress bar give the proper progress when the optional limit argument is used.

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#60]
The CLImate progress bar does give display the proper progress when the optional MIK limit argument is used.

**Comment by MarcusBarnes** [comment]
I have a preliminary fix which I'm currently testing.

**Comment by MarcusBarnes** [comment]
This issue should be addressed in commit 12d87e0b173bb8b6b54887cbf15faba9c2bfa9c9.  If you encounter problems, please reopen this issue.

**Comment by mjordan** [comment]
Thanks! Will test.

**Comment by mjordan** [comment]
Works as intended.
