### ISSUE TITLE
Log problem records as they occur rather than at the end of the script

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#62]
In the main mik foreach loop, log record_keys of records that cause exceptions as they occur, rather than at the end of the script https://github.com/MarcusBarnes/mik/blob/master/mik#L188-L197.  This should help in the event that a machine or network that mik is running makes it impossible to continue processing a collection.   This will make it easier to determine whether one can continue processing on a subset of a collection.

**Comment by mjordan** [comment]
If I can hijack this issue and suggest an improvement to the problem_records.log format - don't overwrite the log (thereby obliterating the list of skipped objects) but instead append to it, adding all items in the .ini file's [CONFIG] section plus a timestamp to the beginning of a job's output of skipped objects.

Let me know if you want a separate issue for this.

**Comment by MarcusBarnes** [comment]
@mjordan That is a good suggestion and doable.  Thank you.

**Comment by MarcusBarnes** [comment]
Commit af3d04f6525b91aa99f53242627e1b1b14845706 addresses this issue while incorporating suggestions from @mjordan  in comment https://github.com/MarcusBarnes/mik/issues/62#issuecomment-136876281.

Note that every time mik is run, the problem_records.log will be initialized with a line containing the CONFIG section of the configuration .ini file used.  Monolog timestamps log entries by default.
