### ISSUE TITLE
CdmNewspapers writer class allowed memory size PHP fatal error for large source files

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#63]
Large source files may cause an allowed memory size PHP fatal error in the CdmNewspaper writer class.  Modify CdmNewspaper writer class to use Guzzle like the CdmPdf and CdmSingle file tool chains to resolve this issue.

**Comment by mjordan** [comment]
@MarcusBarnes is this still an issue?

**Comment by MarcusBarnes** [comment]
@mjordan We were able to process the large CT files with the CdNewpaper writer class without issue after modifications were made after this issue was created.  I'll close this issue.  Should anyone encounter allowed memory size PHP fatal errors for large source files, we can reopen this issue or create a new related issue.  Thanks.
