### ISSUE TITLE
Cdm Book Toolchain

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#65]
An MIK toolchain for migrating books - Create a CONTENTdm book filegetter/writer

The input that Islandora Book Batch expects is documented at https://github.com/Islandora/islandora_book_batch. MIK jobs that migrate books from CONTENTdm would need to use the CdmCompound fetchermanipulator with a document type parameter of 'Monograph'.

One significant difference between CONTENTdm newspapers and monographs is that newspaper issue do not have a hierarchy - all pages are at the same level. CONTENTdm supports hierarchical books.  We may need to flatten hierarchical source books for importing into Islandora since Islandora's Book Solution Pack currently only supports flat books.

**Comment by MarcusBarnes** [comment]
Note that one will need to use the CdmCompound fetcher manipulator for this toolchain: https://github.com/MarcusBarnes/mik/blob/master/src/fetchermanipulators/CdmCompound.php

**Comment by MarcusBarnes** [comment]
The the toolchain is working for non-hierarchical "book" like content that will be imported into Islandora instances using Islandora Book Batch for use with the Islandora Book Solution Pack.   The filegetter assumes that the the source paths contain the CONTENTdm pointer within the file path to the OBJ files for the "book". 

I've put the preliminary code here https://github.com/MarcusBarnes/mik/tree/cdmbooktoolchain while I work on flattening Cdm Monograph (hierarchical) document types.

**Comment by mjordan** [comment]
@MarcusBarnes  was this merged into master with 7827a115d1cc58355c17b146324f4635801403d3?

**Comment by MarcusBarnes** [comment]
@mjordan Thanks.  This issue should have been closed as of commit 09ad0a750da4f4cbf5e10dd80845dfaec56ce409.
