### ISSUE TITLE
Generate a minimal MODS file for newspaper and book pages

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#68]
We should generate a minimal MODS file for each newspaper and book page, like this one:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<mods xmlns="http://www.loc.gov/mods/v3" xmlns:mods="http://www.loc.gov/mods/v3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink">
    <titleInfo>
      <title>Page 1</title>
    </titleInfo>
    <identifier type="uri" invalid="yes" displayLabel="Migrated From">http://content.lib.sfu.ca/cdm/ref/collection/foo/id/1</identifier>
</mods>
```
This will allow for page-level redirects and for better integration with the CONTENTdm API Emulator. It will also let us define the page-level labels rather than rely on the horrible auto-generated labels that the newspaper and book solution packs provide.

Each MODS.xml file will need to be written into the page-level directory in the import package, as in this example:

```
.
├── 1
│   ├── 1
│   │   ├── MODS.xml
│   │   └── OBJ.tiff
│   ├── 2
│   │   ├── MODS.xml
│   │   └── OBJ.tiff
│   ├── 3
│   │   ├── MODS.xml
│   │   └── OBJ.tiff
│   ├── 4
│   │   ├── MODS.xml
│   │   └── OBJ.tiff
│   └── MODS.xml
```

Since these are auto-generated, perhaps we could implement this via a metadata or file manipulator?

**Comment by MarcusBarnes** [comment]
Commit 6c1cb256bec46c03ac11a71ddaaadf7c22a634bd is a first go at making minimal page level mods available for the CDM newspaper toolchain.  Further changes may be needed depending on the needs of the CONTENTdm API Emulator and to enhance the logical structure of the MIK source code.
