### ISSUE TITLE
Add a filemanipulator that gets compound objects' .cpd file

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#69]
We need to ingest compound objects' .cpd files, in order to support CONTENTdm API emulation via https://github.com/mjordan/islandora_cdm_api (see https://github.com/mjordan/islandora_cdm_api/issues/2 for example). The resulting datastream should probably have a DS ID of 'CDMCPD'.

**Comment by mjordan** [comment]
Filegetters don't have a generalized way of calling filegettermaniplators. ThumbnailFromCdm is hardcoded in CdmNewspapers. Also, to get this to work, filemanipulators need to implement a ->manuipulate() method, like metadata manipulators do.

I can take a stab at implementing this.

**Comment by mjordan** [comment]
In the interest of saving time, I'd recommend we hard-code getting the CPD file in the CdmNewspapers filegetter and when they're ready, the book and generic compound filegetters. We can figure out later the best way to integrate this functionality as manipulators.

**Comment by MarcusBarnes** [comment]
Work on [issue-69](https://github.com/MarcusBarnes/mik/issues/69) with respect to @mjordan's comment https://github.com/MarcusBarnes/mik/issues/69#issuecomment-142486310  has been merged into master at commit d47fe825aeeafde8e8fba43d8792751640bc51b2.  Thank you @mjordan for your work adding this functionality.

It might be good to keep branch [issue-69]https://github.com/MarcusBarnes/mik/tree/issue-69) for reference when there is later work on integrating the functionality as manipulators.
