### ISSUE TITLE
Extras: output package checker - all expected files present?

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#71]
Provide a QA tool as part of the extras that will double check the output packages from MIK to verify that all files that are expected are present.

Here is an example scenario for the CdmNewspaper toolchain. A newspaper collection is processed by a user, but one or more issues cause exceptions while writing the package for the issues.  These issues were properly logged in the problem_records.log on the user's machine.  The user does not check check the problem_records.log and moves onto other work.  Coming back later to the packages created for the newspaper collection, another user assume that the entire collection has been processed without any exceptions or problems. The newspaper issue corresponding a problem_record may not have all the files expected (datastreams in the Islandora context).

The tool would take the path for the directory containing the packages output by MIK, the expected output model (for example, newspapers) and a list of expected datastreams, iterate through the subdirectories making up MIK output packages, and return a list of directories that do not contain all the expected files.

There would be no need for this tool assuming a perfect package creation workflow, but given that MIK may be used as part of large migrations, additional workflow checks such as this tool may prove useful as an extra.

**Comment by mjordan** [comment]
I like this idea. Would be add a "on completion" hook mechanism or similar to the main mik script so we could add it to toolchains?

**Comment by mjordan** [comment]
Currently, the script assumes that MODS.xml is the issue-level metadata file. Newspaper batch allows MODS, DC or MARCXML (.xml). Maybe we should add an optional command-line option  (with a default of MODS.xml) so the user can specific which one to check for at the newspaper issue level, e.gi `--issue_level_metadata=DC.xml`.

**Comment by MarcusBarnes** [comment]
Capturing a thought related to comment https://github.com/MarcusBarnes/mik/issues/71#issuecomment-145261972:  For the extras scripts, provide an option to return a boolean value or values to be handed off to the next extras script so that these can be chained when using an on-completion mechanism.

**Comment by MarcusBarnes** [comment]
I've tested both newspaper and single item packages with the check_files.php extras script.  It functioned as expected.  I will close this issue and merge into master.  Additional enhancements such as that suggested in comment https://github.com/MarcusBarnes/mik/issues/71#issuecomment-156132600 can be added as separate issues.

**Comment by MarcusBarnes** [comment]
Address in commit 31ce77e5d75ea46d5ec6c9ae3389bb4ba7146786.
