### ISSUE TITLE
CdmNewspaper Toolchain: Handle input_directories for OJB files that may not be locally accessible directories?

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#72]
The CdmNewspaper toolchain assumes that the input_directories[] as part of the FILE_GETTER configuration are accessible via the local environment for retrieving the OBJ.TIFF.  For example, via mounted network drives where the user has permissions to read files on the mounted drive and a full path to the drives is provided in the input_directories[] settings in the FILE_GETTER section of the associated configuration file.

Is it desirable to have the toolchain fetch the OBJ.tiff via HTTP or other URI schemes?

**Comment by mjordan** [comment]
I'm satisfied with supporting only locally accessible directories until we have a need to support anything else.
