### ISSUE TITLE
FYI: (Windows) Paths in the configuration file may make MIK fail if they include junction points.

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#76]
If mounted Window share drives include junction points for input_directories[] or output_directory paths in the configuration file, MIK filgetters or writers may fail.  

Temporary solution is to use paths that do not include junctions.

**Comment by mjordan** [comment]
@MarcusBarnes I've added a note about this to https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Running-MIK-on-Windows, closing.
