### ISSUE TITLE
Create fetcher manipulator for Cdm toolchains that filters out compound child objects

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#83]
The generic compound object toolchain under development will migrate single-file CONTENTdm objects that are children of compound objects. To ensure that we don't load the same single-file object twice, we need to be able to perform a migration of only parentless single-file objects, that is, ones that have a 'find' field value of -1.

**Comment by mjordan** [comment]
@mbarnes, can you test issue-83 branch when you have a minute? [Wiki page](https://github.com/MarcusBarnes/mik/wiki/Fetcher-manipulator:-CdmNoParent) is available.

**Comment by MarcusBarnes** [comment]
@mjordan Yes.  I will test and report back.

**Comment by MarcusBarnes** [comment]
Initial test runs on my end create output as expected.

**Comment by MarcusBarnes** [comment]
Addressed in commit 2889a0b8cb145700d24c33cae77b2b1c87bc235b.
