### ISSUE TITLE
Create a metadta manuipulator that adds a UUID to a MODS identifier element

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#84]
Similar to the AddContentdmData manipulator, this one would simply add a V4 UUID to a MODS identifier element. Use the Composer-friendly https://github.com/ramsey/uuid to generate the UUIDs since PHP can't seem to do that.

**Comment by mjordan** [comment]
@MarcusBarnes if you could test this on a Windows box I'd appreciate it. The code is in the issue-84 branch, and you will need to run composer update before running MIK. I've added a wiki page for this manipulator that explains what it does.

**Comment by MarcusBarnes** [comment]
@mjordan Thanks - I'll test this on a Windows box and report back.

**Comment by MarcusBarnes** [comment]
I've tested the code with the CdmNewspaper toolchain on a Windows 7 box and the UUID is added to the issue level MODS XML as expected. :thumbsup:

**Comment by mjordan** [comment]
Excellent, thanks. Please merge and delete branch issue-84 at your convenience.
