### ISSUE TITLE
Add ability to CdmSingleFile file getter to get masters

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#85]
CdmSingleFile.php does not get master files from local drives like CdmNewspapers.php does. Should work the same way it does now for newspapers.

**Comment by mjordan** [comment]
I'll make a first pass at this feature this weekend.

**Comment by mjordan** [comment]
@MarcusBarnes can we close this issue?

**Comment by MarcusBarnes** [comment]
Yes, as the work was merged into master.  Thanks again @mjordan for your contribution.
