### ISSUE TITLE
CdmNewspaper toolchain: V4 UUID for page-level MODS XML

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/mik#88]
Add a V4 UUID to the page-level MODS XML generated from the CdmNewspaper toochain when `datastreams[] = MODS` (for page level MODS XML) is set for in the WRITER section of the MIK configuration file and the ` metadatamanipulators[] = "AddUuidToMods"` is set in the MANIPULATORS section. See the wiki page for the [AddUuidtoMods metadata manipulator](https://github.com/MarcusBarnes/mik/wiki/Metadata-manipulator:-AddUuidToMods).

**Comment by MarcusBarnes** [comment]
Addressed in commit https://github.com/MarcusBarnes/mik/commit/d75ca3eb3ba0f6bb3d9b20f385f60af35fcf635f.

**Comment by mjordan** [comment]
Great, I'll give this a whirl this evening.

**Comment by MarcusBarnes** [comment]
@mjordan Thank you.
