### ISSUE TITLE
Add option to check_files.php to allow for metadata other than MODS.xml

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#90]
Based on https://github.com/MarcusBarnes/mik/issues/71#issuecomment-156132600.

Add an option to extras/check_files.php to allow the user to indicate DC.xml or MARCXML.xml as the issue-level metadata to check for. Currently, MODS.xml is hard coded.

**Comment by MarcusBarnes** [comment]
This feature enhancement was merged into master at https://github.com/MarcusBarnes/mik/commit/c463e7018018e5c9fbc56f16cedffddd2210e6c1.
