### ISSUE TITLE
Use cases for conditional mapping from source to output metadata structures

### ISSUE THREAD

**Issue by mjordan** [MarcusBarnes/mik#99]
Currently, the source->output mappings that MIK does can't accommodate conditional logic; the mappings are strictly one to one, from source to output, with at most the value of the source element interpolated into the output XML snippet through use of the %value% token. This issue is a place to collect use cases for adding conditional logic to the mappings.

**Comment by mjordan** [comment]
Use case: If an element already exists in the output document, skip a metadata manipulator or mapping.

Example: An `<identifier>` element already exists in the metadata (for example, as defined in a mapping file), so we don't want to add an additional one that has the same attribute or value.

**Comment by mjordan** [comment]
This is not a use case but a possible way to allow metadata manipulators to use a simple "session" to track information about XML elements they have already processed. Basically, this allows metadata manipulators to write data to a file and then retrieve it later. I've implemented this for discussion in https://github.com/MarcusBarnes/mik/blob/session/src/metadatamanipulators/MetadataManipulator.php by adding a writeSession() and a readSession() method to the MetadataManipulator abstract class, and by providing an example implementation of those methods in https://github.com/MarcusBarnes/mik/blob/session/src/metadatamanipulators/AddUuidToMods.php.

@MarcusBarnes can you review and let me know if you see any issues with this?

**Comment by mjordan** [comment]
Some basic documentation for using the session:

Metadata manipulators process a single MODS element, not the entire MODS XML document. This means that they inspect and modify elements in isolation from the rest of the XML document, which makes it impossible to do things like check for the existence of an element other than the one being manipulated, or to inspect the value of another element and manipulate the current element based on that content.

In order to provide a way for metadata manipulators to "remember' information about elements that a they have already processed, they can write arbitrary data to a session file and then retrieve that data later. The session applies to each MODS document, not to the entire MIK job. The two methods that provide access to this session data are `writeSession()` and `readSession)`. For example, to avoid adding an element that already exists in a MODS document, you would use a pattern like this:

```
// If the MODS contains a <note> element, add a flag to the
// session to we can avoid adding a second one later.
$note_already_present = true;
$this->writeSession(serialize($note_already_present));
```

Then, when your metadata manipulator wants to add a `<note>` element, you can retrieve the data you added to the session when you checked for the existence of a note and inspect it:

```
// Only add a new <note> element if there is no flag
// in the session indicating we've alredy found one
// in the MODS document.
$session = $this->readSession();
if (!unserialize($session)) {
    // Add the <note> element, since the session indicates there isn't already one.
 }
```

The data that you add to the session is up to you. Serializing your data is optional but doing so allows you to store complex data, not just strings.

**Comment by MarcusBarnes** [comment]
@mjordan Awesome! Thank you for the contribution.  I will review and report any issues I encounter.  Thanks again.

**Comment by mjordan** [comment]
Great. I'm going to add something else to the basic documentation comment now.

**Comment by mjordan** [comment]
@MarcusBarnes with the new metadata caching feature in 6192d0880a8e08d47c12fffdda8df78227e0e93f, it will be possible for metadata manipulators to access the raw metadata and react accordingly. So the caveat I expressed above, "Keep in mind that the elements in the MODS document are processed sequentially", may not be as big deal.

Would you mind testing the "session" branch to make sure it works? We may want to change the extension of the session file from .dat to .session at https://github.com/MarcusBarnes/mik/commit/10b462ee423acb7c83af5a3f5089dc61bb0c422b#diff-0a6431f6b2f3ff265f9170f065135973R37 to clarify what the file does and to minimize the possibility of filename conflicts in the temp directory. Or, create a 'session' subdirectory within the temp directory to keep concerns separated.

Let me know if you'd like some suggestions for how to test.

**Comment by MarcusBarnes** [comment]
@mjordan Yes - I'll test the session branch.   Please provide any suggested scenarios for the testing.  Thank you!

**Comment by mjordan** [comment]
To test the latter approach using the cartoons data, in *master* branch do the following:

1. Add the [sample metadata manipulator](https://gist.github.com/mjordan/9f5813dd99281ddb2ff7)  to your toolchain (copy it to src/metadatamanipulators/MJTest.php, run `composer 1. dum-autoload`, and add `metadatamanipulators[] = "MJTest"` to your config file).
1. Add `null6,<extension><foo></foo></extension>` to your mappings file
1. Run MIK using the cartoons configuration file. 
1. Change the conditional logic at lines 64 and following in the manipulator if you want.

I am wondering now if we even need a session - seems to me that it's redundant if we can inspect any part of the cached raw metadata as done in the sample manipulator. What do you think?

**Comment by mjordan** [comment]
Now that I reread the original use case that I supplied, there might still be a use for the session, since it saves the XML for later inspection. There might be a use for both approaches.

**Comment by MarcusBarnes** [comment]
@mjordan I have tested the scenario described in your your [comment](https://github.com/MarcusBarnes/mik/issues/99#issuecomment-170264456).  It worked as expected.  Very cool.  Thank you.

**Comment by mjordan** [comment]
Thanks. Maybe I'll write up a cookbook recipe based on this technique, on "How do I modify the value of a MODS element based on specific metadata values?" or something similar? Seems like a useful topic.

**Comment by MarcusBarnes** [comment]
@mjordan Great idea.  Thanks.

**Comment by mjordan** [comment]
@MarcusBarnes if you've tested the session branch, could you merge it into master? There is some code that is in the Metadtamanipulator abstract class that should be merged. The second, cached metadata, approach doesn't use any code outside of manipulators so there's nothing to merge for that.

**Comment by MarcusBarnes** [comment]
@mjordan I'm not done testing the session branch.  It did not run as expected on my machine for the cartoon test Csv test data.  I haven't yet been able to determine why it's not generating the packages as expected.

**Comment by mjordan** [comment]
I'm happy to help troubleshoot tomorrow when I'm in the office.

**Comment by MarcusBarnes** [comment]
@mjordan Thanks.

**Comment by mjordan** [comment]
I think the InsertXmlFromTemplate metadata manipulator ([examples](https://github.com/MarcusBarnes/mik/tree/master/extras/bceln)) and the Templated metadata parser ([examples](https://github.com/MarcusBarnes/mik/wiki/Cookbook:-Templated-Metadata-Parser)) makes this issue redundant, since in it you can use Twig's control structures to do all sorts of complex stuff. Thoughts?

**Comment by mjordan** [comment]
Closing.
